[package]
name = "roto-svc-sts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
diesel = { version = "2.3.14", default-features = false, features = ["sqlite", "32-column-tables", "returning_clauses_for_sqlite_3_35"] }
roto-core = { version = "0.0.1", path = "../roto-core" }
roto-protocol = { version = "0.0.1", path = "../roto-protocol" }
roto-svc-iam = { version = "0.0.1", path = "../roto-svc-iam" }
roxmltree = "0.21.1"
uuid = { version = "1.27.0", features = ["v4"] }
