[package]
name = "roto-svc-secretsmanager"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
roto-core = { version = "0.0.1", path = "../roto-core" }
roto-protocol = { version = "0.0.1", path = "../roto-protocol" }
serde_json = "1.0.151"
uuid = { version = "1.27.0", features = ["v4"] }
