[package]
name = "roto-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum = "0.8.9"
clap = { version = "4.6.7", features = ["derive", "env"] }
roto-core = { version = "0.0.1", path = "../roto-core" }
roto-svc-dynamodb = { version = "0.0.1", path = "../roto-svc-dynamodb" }
roto-svc-iam = { version = "0.0.1", path = "../roto-svc-iam" }
roto-svc-lambda = { version = "0.0.1", path = "../roto-svc-lambda" }
roto-svc-s3 = { version = "0.0.1", path = "../roto-svc-s3" }
roto-svc-secretsmanager = { version = "0.0.1", path = "../roto-svc-secretsmanager" }
roto-svc-sns = { version = "0.0.1", path = "../roto-svc-sns" }
roto-svc-sqs = { version = "0.0.1", path = "../roto-svc-sqs" }
roto-svc-ssm = { version = "0.0.1", path = "../roto-svc-ssm" }
roto-svc-sts = { version = "0.0.1", path = "../roto-svc-sts" }
tokio = { version = "1.53.2", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
mlua = { version = "0.12.2", features = ["lua54", "vendored", "serde"] }
serde_json = "1.0.151"
roto-protocol = { version = "0.0.1", path = "../roto-protocol" }
