[package]
name = "roto-svc-eventbridge"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
roto-core = { version = "0.0.1", path = "../roto-core" }
roto-protocol = { version = "0.0.1", path = "../roto-protocol" }
roto-svc-lambda = { version = "0.0.1", path = "../roto-svc-lambda" }
roto-svc-sqs = { version = "0.0.1", path = "../roto-svc-sqs" }
serde_json = "1.0.151"
