// @generated by roto-codegen from the botocore model. DO NOT EDIT.
#![allow(clippy::all, dead_code, unused_variables, unused_mut, unused_imports)]

use roto_core::{AwsError, RawResponse, RequestContext};
use roto_protocol::json::{as_object, member};
use roto_protocol::{Blob, FromJson, JsonValue, Timestamp, ToJson, json_response};
use serde_json::{Map, Value};
use std::collections::BTreeMap;

pub const JSON_VERSION: &str = "1.1";
pub const TARGET_PREFIX: &str = "secretsmanager";
pub const QUERY_COMPATIBLE: bool = false;
pub const API_VERSION: &str = "2017-10-17";

/// (operation, supported by the generated codec)
pub const OPERATIONS: &[(&str, bool)] = &[
    ("BatchGetSecretValue", true),
    ("CancelRotateSecret", true),
    ("CreateSecret", true),
    ("DeleteResourcePolicy", true),
    ("DeleteSecret", true),
    ("DescribeSecret", true),
    ("GetRandomPassword", true),
    ("GetResourcePolicy", true),
    ("GetSecretValue", true),
    ("ListSecretVersionIds", true),
    ("ListSecrets", true),
    ("PutResourcePolicy", true),
    ("PutSecretValue", true),
    ("RemoveRegionsFromReplication", true),
    ("ReplicateSecretToRegions", true),
    ("RestoreSecret", true),
    ("RotateSecret", true),
    ("StopReplicationToReplica", true),
    ("TagResource", true),
    ("UntagResource", true),
    ("UpdateSecret", true),
    ("UpdateSecretVersionStage", true),
    ("ValidateResourcePolicy", true),
];

#[derive(Debug, Clone, Default, PartialEq)]
pub struct APIErrorType {
    pub error_code: Option<String>,
    pub message: Option<String>,
    pub secret_id: Option<String>,
}

impl FromJson for APIErrorType {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            error_code: member(o, "ErrorCode", path)?,
            message: member(o, "Message", path)?,
            secret_id: member(o, "SecretId", path)?,
        };
        Ok(s)
    }
}

impl ToJson for APIErrorType {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.error_code {
            o.insert("ErrorCode".into(), v.to_json());
        }
        if let Some(v) = &self.message {
            o.insert("Message".into(), v.to_json());
        }
        if let Some(v) = &self.secret_id {
            o.insert("SecretId".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BatchGetSecretValueRequest {
    pub filters: Vec<Filter>,
    pub max_results: Option<i32>,
    pub next_token: Option<String>,
    pub secret_id_list: Vec<String>,
}

impl FromJson for BatchGetSecretValueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            filters: member(o, "Filters", path)?.unwrap_or_default(),
            max_results: member(o, "MaxResults", path)?,
            next_token: member(o, "NextToken", path)?,
            secret_id_list: member(o, "SecretIdList", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for BatchGetSecretValueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.filters.is_empty() {
            o.insert("Filters".into(), self.filters.to_json());
        }
        if let Some(v) = &self.max_results {
            o.insert("MaxResults".into(), v.to_json());
        }
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        if !self.secret_id_list.is_empty() {
            o.insert("SecretIdList".into(), self.secret_id_list.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BatchGetSecretValueResponse {
    pub errors: Vec<APIErrorType>,
    pub next_token: Option<String>,
    pub secret_values: Vec<SecretValueEntry>,
}

impl FromJson for BatchGetSecretValueResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            errors: member(o, "Errors", path)?.unwrap_or_default(),
            next_token: member(o, "NextToken", path)?,
            secret_values: member(o, "SecretValues", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for BatchGetSecretValueResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.errors.is_empty() {
            o.insert("Errors".into(), self.errors.to_json());
        }
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        o.insert("SecretValues".into(), self.secret_values.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CancelRotateSecretRequest {
    pub secret_id: String,
}

impl FromJson for CancelRotateSecretRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for CancelRotateSecretRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CancelRotateSecretResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
    pub version_id: Option<String>,
}

impl FromJson for CancelRotateSecretResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
            version_id: member(o, "VersionId", path)?,
        };
        Ok(s)
    }
}

impl ToJson for CancelRotateSecretResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CreateSecretRequest {
    pub add_replica_regions: Vec<ReplicaRegionType>,
    pub client_request_token: Option<String>,
    pub description: Option<String>,
    pub force_overwrite_replica_secret: Option<bool>,
    pub kms_key_id: Option<String>,
    pub name: String,
    pub secret_binary: Option<Blob>,
    pub secret_string: Option<String>,
    pub tags: Vec<Tag>,
    pub r#type: Option<String>,
}

impl FromJson for CreateSecretRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            add_replica_regions: member(o, "AddReplicaRegions", path)?.unwrap_or_default(),
            client_request_token: member(o, "ClientRequestToken", path)?,
            description: member(o, "Description", path)?,
            force_overwrite_replica_secret: member(o, "ForceOverwriteReplicaSecret", path)?,
            kms_key_id: member(o, "KmsKeyId", path)?,
            name: member(o, "Name", path)?.ok_or_else(|| AwsError::missing_parameter("Name"))?,
            secret_binary: member(o, "SecretBinary", path)?,
            secret_string: member(o, "SecretString", path)?,
            tags: member(o, "Tags", path)?.unwrap_or_default(),
            r#type: member(o, "Type", path)?,
        };
        Ok(s)
    }
}

impl ToJson for CreateSecretRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.add_replica_regions.is_empty() {
            o.insert(
                "AddReplicaRegions".into(),
                self.add_replica_regions.to_json(),
            );
        }
        if let Some(v) = &self.client_request_token {
            o.insert("ClientRequestToken".into(), v.to_json());
        }
        if let Some(v) = &self.description {
            o.insert("Description".into(), v.to_json());
        }
        if let Some(v) = &self.force_overwrite_replica_secret {
            o.insert("ForceOverwriteReplicaSecret".into(), v.to_json());
        }
        if let Some(v) = &self.kms_key_id {
            o.insert("KmsKeyId".into(), v.to_json());
        }
        o.insert("Name".into(), self.name.to_json());
        if let Some(v) = &self.secret_binary {
            o.insert("SecretBinary".into(), v.to_json());
        }
        if let Some(v) = &self.secret_string {
            o.insert("SecretString".into(), v.to_json());
        }
        if !self.tags.is_empty() {
            o.insert("Tags".into(), self.tags.to_json());
        }
        if let Some(v) = &self.r#type {
            o.insert("Type".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CreateSecretResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
    pub replication_status: Vec<ReplicationStatusType>,
    pub version_id: Option<String>,
}

impl FromJson for CreateSecretResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
            replication_status: member(o, "ReplicationStatus", path)?.unwrap_or_default(),
            version_id: member(o, "VersionId", path)?,
        };
        Ok(s)
    }
}

impl ToJson for CreateSecretResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if !self.replication_status.is_empty() {
            o.insert(
                "ReplicationStatus".into(),
                self.replication_status.to_json(),
            );
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteResourcePolicyRequest {
    pub secret_id: String,
}

impl FromJson for DeleteResourcePolicyRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteResourcePolicyRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteResourcePolicyResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
}

impl FromJson for DeleteResourcePolicyResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteResourcePolicyResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteSecretRequest {
    pub force_delete_without_recovery: Option<bool>,
    pub recovery_window_in_days: Option<i64>,
    pub secret_id: String,
}

impl FromJson for DeleteSecretRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            force_delete_without_recovery: member(o, "ForceDeleteWithoutRecovery", path)?,
            recovery_window_in_days: member(o, "RecoveryWindowInDays", path)?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteSecretRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.force_delete_without_recovery {
            o.insert("ForceDeleteWithoutRecovery".into(), v.to_json());
        }
        if let Some(v) = &self.recovery_window_in_days {
            o.insert("RecoveryWindowInDays".into(), v.to_json());
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteSecretResponse {
    pub arn: Option<String>,
    pub deletion_date: Option<Timestamp>,
    pub name: Option<String>,
}

impl FromJson for DeleteSecretResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            deletion_date: member(o, "DeletionDate", path)?,
            name: member(o, "Name", path)?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteSecretResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.deletion_date {
            o.insert("DeletionDate".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DescribeSecretRequest {
    pub secret_id: String,
}

impl FromJson for DescribeSecretRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for DescribeSecretRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DescribeSecretResponse {
    pub arn: Option<String>,
    pub created_date: Option<Timestamp>,
    pub deleted_date: Option<Timestamp>,
    pub description: Option<String>,
    pub external_secret_rotation_metadata: Vec<ExternalSecretRotationMetadataItem>,
    pub external_secret_rotation_role_arn: Option<String>,
    pub kms_key_id: Option<String>,
    pub last_accessed_date: Option<Timestamp>,
    pub last_changed_date: Option<Timestamp>,
    pub last_rotated_date: Option<Timestamp>,
    pub name: Option<String>,
    pub next_rotation_date: Option<Timestamp>,
    pub owning_service: Option<String>,
    pub primary_region: Option<String>,
    pub replication_status: Vec<ReplicationStatusType>,
    pub rotation_enabled: Option<bool>,
    pub rotation_lambda_arn: Option<String>,
    pub rotation_rules: Option<RotationRulesType>,
    pub tags: Vec<Tag>,
    pub r#type: Option<String>,
    pub version_ids_to_stages: BTreeMap<String, Vec<String>>,
}

impl FromJson for DescribeSecretResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            created_date: member(o, "CreatedDate", path)?,
            deleted_date: member(o, "DeletedDate", path)?,
            description: member(o, "Description", path)?,
            external_secret_rotation_metadata: member(o, "ExternalSecretRotationMetadata", path)?
                .unwrap_or_default(),
            external_secret_rotation_role_arn: member(o, "ExternalSecretRotationRoleArn", path)?,
            kms_key_id: member(o, "KmsKeyId", path)?,
            last_accessed_date: member(o, "LastAccessedDate", path)?,
            last_changed_date: member(o, "LastChangedDate", path)?,
            last_rotated_date: member(o, "LastRotatedDate", path)?,
            name: member(o, "Name", path)?,
            next_rotation_date: member(o, "NextRotationDate", path)?,
            owning_service: member(o, "OwningService", path)?,
            primary_region: member(o, "PrimaryRegion", path)?,
            replication_status: member(o, "ReplicationStatus", path)?.unwrap_or_default(),
            rotation_enabled: member(o, "RotationEnabled", path)?,
            rotation_lambda_arn: member(o, "RotationLambdaARN", path)?,
            rotation_rules: member(o, "RotationRules", path)?,
            tags: member(o, "Tags", path)?.unwrap_or_default(),
            r#type: member(o, "Type", path)?,
            version_ids_to_stages: member(o, "VersionIdsToStages", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for DescribeSecretResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.created_date {
            o.insert("CreatedDate".into(), v.to_json());
        }
        if let Some(v) = &self.deleted_date {
            o.insert("DeletedDate".into(), v.to_json());
        }
        if let Some(v) = &self.description {
            o.insert("Description".into(), v.to_json());
        }
        if !self.external_secret_rotation_metadata.is_empty() {
            o.insert(
                "ExternalSecretRotationMetadata".into(),
                self.external_secret_rotation_metadata.to_json(),
            );
        }
        if let Some(v) = &self.external_secret_rotation_role_arn {
            o.insert("ExternalSecretRotationRoleArn".into(), v.to_json());
        }
        if let Some(v) = &self.kms_key_id {
            o.insert("KmsKeyId".into(), v.to_json());
        }
        if let Some(v) = &self.last_accessed_date {
            o.insert("LastAccessedDate".into(), v.to_json());
        }
        if let Some(v) = &self.last_changed_date {
            o.insert("LastChangedDate".into(), v.to_json());
        }
        if let Some(v) = &self.last_rotated_date {
            o.insert("LastRotatedDate".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.next_rotation_date {
            o.insert("NextRotationDate".into(), v.to_json());
        }
        if let Some(v) = &self.owning_service {
            o.insert("OwningService".into(), v.to_json());
        }
        if let Some(v) = &self.primary_region {
            o.insert("PrimaryRegion".into(), v.to_json());
        }
        if !self.replication_status.is_empty() {
            o.insert(
                "ReplicationStatus".into(),
                self.replication_status.to_json(),
            );
        }
        if let Some(v) = &self.rotation_enabled {
            o.insert("RotationEnabled".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_lambda_arn {
            o.insert("RotationLambdaARN".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_rules {
            o.insert("RotationRules".into(), v.to_json());
        }
        o.insert("Tags".into(), self.tags.to_json());
        if let Some(v) = &self.r#type {
            o.insert("Type".into(), v.to_json());
        }
        if !self.version_ids_to_stages.is_empty() {
            o.insert(
                "VersionIdsToStages".into(),
                self.version_ids_to_stages.to_json(),
            );
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ExternalSecretRotationMetadataItem {
    pub key: Option<String>,
    pub value: Option<String>,
}

impl FromJson for ExternalSecretRotationMetadataItem {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            key: member(o, "Key", path)?,
            value: member(o, "Value", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ExternalSecretRotationMetadataItem {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.key {
            o.insert("Key".into(), v.to_json());
        }
        if let Some(v) = &self.value {
            o.insert("Value".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filter {
    pub key: Option<String>,
    pub values: Vec<String>,
}

impl FromJson for Filter {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            key: member(o, "Key", path)?,
            values: member(o, "Values", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for Filter {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.key {
            o.insert("Key".into(), v.to_json());
        }
        if !self.values.is_empty() {
            o.insert("Values".into(), self.values.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetRandomPasswordRequest {
    pub exclude_characters: Option<String>,
    pub exclude_lowercase: Option<bool>,
    pub exclude_numbers: Option<bool>,
    pub exclude_punctuation: Option<bool>,
    pub exclude_uppercase: Option<bool>,
    pub include_space: Option<bool>,
    pub password_length: Option<i64>,
    pub require_each_included_type: Option<bool>,
}

impl FromJson for GetRandomPasswordRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            exclude_characters: member(o, "ExcludeCharacters", path)?,
            exclude_lowercase: member(o, "ExcludeLowercase", path)?,
            exclude_numbers: member(o, "ExcludeNumbers", path)?,
            exclude_punctuation: member(o, "ExcludePunctuation", path)?,
            exclude_uppercase: member(o, "ExcludeUppercase", path)?,
            include_space: member(o, "IncludeSpace", path)?,
            password_length: member(o, "PasswordLength", path)?,
            require_each_included_type: member(o, "RequireEachIncludedType", path)?,
        };
        Ok(s)
    }
}

impl ToJson for GetRandomPasswordRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.exclude_characters {
            o.insert("ExcludeCharacters".into(), v.to_json());
        }
        if let Some(v) = &self.exclude_lowercase {
            o.insert("ExcludeLowercase".into(), v.to_json());
        }
        if let Some(v) = &self.exclude_numbers {
            o.insert("ExcludeNumbers".into(), v.to_json());
        }
        if let Some(v) = &self.exclude_punctuation {
            o.insert("ExcludePunctuation".into(), v.to_json());
        }
        if let Some(v) = &self.exclude_uppercase {
            o.insert("ExcludeUppercase".into(), v.to_json());
        }
        if let Some(v) = &self.include_space {
            o.insert("IncludeSpace".into(), v.to_json());
        }
        if let Some(v) = &self.password_length {
            o.insert("PasswordLength".into(), v.to_json());
        }
        if let Some(v) = &self.require_each_included_type {
            o.insert("RequireEachIncludedType".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetRandomPasswordResponse {
    pub random_password: Option<String>,
}

impl FromJson for GetRandomPasswordResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            random_password: member(o, "RandomPassword", path)?,
        };
        Ok(s)
    }
}

impl ToJson for GetRandomPasswordResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.random_password {
            o.insert("RandomPassword".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetResourcePolicyRequest {
    pub secret_id: String,
}

impl FromJson for GetResourcePolicyRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for GetResourcePolicyRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetResourcePolicyResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
    pub resource_policy: Option<String>,
}

impl FromJson for GetResourcePolicyResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
            resource_policy: member(o, "ResourcePolicy", path)?,
        };
        Ok(s)
    }
}

impl ToJson for GetResourcePolicyResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.resource_policy {
            o.insert("ResourcePolicy".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetSecretValueRequest {
    pub secret_id: String,
    pub version_id: Option<String>,
    pub version_stage: Option<String>,
}

impl FromJson for GetSecretValueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
            version_id: member(o, "VersionId", path)?,
            version_stage: member(o, "VersionStage", path)?,
        };
        Ok(s)
    }
}

impl ToJson for GetSecretValueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        if let Some(v) = &self.version_stage {
            o.insert("VersionStage".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetSecretValueResponse {
    pub arn: Option<String>,
    pub created_date: Option<Timestamp>,
    pub name: Option<String>,
    pub secret_binary: Option<Blob>,
    pub secret_string: Option<String>,
    pub version_id: Option<String>,
    pub version_stages: Vec<String>,
}

impl FromJson for GetSecretValueResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            created_date: member(o, "CreatedDate", path)?,
            name: member(o, "Name", path)?,
            secret_binary: member(o, "SecretBinary", path)?,
            secret_string: member(o, "SecretString", path)?,
            version_id: member(o, "VersionId", path)?,
            version_stages: member(o, "VersionStages", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for GetSecretValueResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.created_date {
            o.insert("CreatedDate".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.secret_binary {
            o.insert("SecretBinary".into(), v.to_json());
        }
        if let Some(v) = &self.secret_string {
            o.insert("SecretString".into(), v.to_json());
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        if !self.version_stages.is_empty() {
            o.insert("VersionStages".into(), self.version_stages.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListSecretVersionIdsRequest {
    pub include_deprecated: Option<bool>,
    pub max_results: Option<i32>,
    pub next_token: Option<String>,
    pub secret_id: String,
}

impl FromJson for ListSecretVersionIdsRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            include_deprecated: member(o, "IncludeDeprecated", path)?,
            max_results: member(o, "MaxResults", path)?,
            next_token: member(o, "NextToken", path)?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for ListSecretVersionIdsRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.include_deprecated {
            o.insert("IncludeDeprecated".into(), v.to_json());
        }
        if let Some(v) = &self.max_results {
            o.insert("MaxResults".into(), v.to_json());
        }
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListSecretVersionIdsResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
    pub next_token: Option<String>,
    pub versions: Vec<SecretVersionsListEntry>,
}

impl FromJson for ListSecretVersionIdsResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
            next_token: member(o, "NextToken", path)?,
            versions: member(o, "Versions", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ListSecretVersionIdsResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        o.insert("Versions".into(), self.versions.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListSecretsRequest {
    pub filters: Vec<Filter>,
    pub include_planned_deletion: Option<bool>,
    pub max_results: Option<i32>,
    pub next_token: Option<String>,
    pub sort_by: Option<String>,
    pub sort_order: Option<String>,
}

impl FromJson for ListSecretsRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            filters: member(o, "Filters", path)?.unwrap_or_default(),
            include_planned_deletion: member(o, "IncludePlannedDeletion", path)?,
            max_results: member(o, "MaxResults", path)?,
            next_token: member(o, "NextToken", path)?,
            sort_by: member(o, "SortBy", path)?,
            sort_order: member(o, "SortOrder", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ListSecretsRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.filters.is_empty() {
            o.insert("Filters".into(), self.filters.to_json());
        }
        if let Some(v) = &self.include_planned_deletion {
            o.insert("IncludePlannedDeletion".into(), v.to_json());
        }
        if let Some(v) = &self.max_results {
            o.insert("MaxResults".into(), v.to_json());
        }
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        if let Some(v) = &self.sort_by {
            o.insert("SortBy".into(), v.to_json());
        }
        if let Some(v) = &self.sort_order {
            o.insert("SortOrder".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListSecretsResponse {
    pub next_token: Option<String>,
    pub secret_list: Vec<SecretListEntry>,
}

impl FromJson for ListSecretsResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            next_token: member(o, "NextToken", path)?,
            secret_list: member(o, "SecretList", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ListSecretsResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        o.insert("SecretList".into(), self.secret_list.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PutResourcePolicyRequest {
    pub block_public_policy: Option<bool>,
    pub resource_policy: String,
    pub secret_id: String,
}

impl FromJson for PutResourcePolicyRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            block_public_policy: member(o, "BlockPublicPolicy", path)?,
            resource_policy: member(o, "ResourcePolicy", path)?
                .ok_or_else(|| AwsError::missing_parameter("ResourcePolicy"))?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for PutResourcePolicyRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.block_public_policy {
            o.insert("BlockPublicPolicy".into(), v.to_json());
        }
        o.insert("ResourcePolicy".into(), self.resource_policy.to_json());
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PutResourcePolicyResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
}

impl FromJson for PutResourcePolicyResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
        };
        Ok(s)
    }
}

impl ToJson for PutResourcePolicyResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PutSecretValueRequest {
    pub client_request_token: Option<String>,
    pub rotation_token: Option<String>,
    pub secret_binary: Option<Blob>,
    pub secret_id: String,
    pub secret_string: Option<String>,
    pub version_stages: Vec<String>,
}

impl FromJson for PutSecretValueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            client_request_token: member(o, "ClientRequestToken", path)?,
            rotation_token: member(o, "RotationToken", path)?,
            secret_binary: member(o, "SecretBinary", path)?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
            secret_string: member(o, "SecretString", path)?,
            version_stages: member(o, "VersionStages", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for PutSecretValueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.client_request_token {
            o.insert("ClientRequestToken".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_token {
            o.insert("RotationToken".into(), v.to_json());
        }
        if let Some(v) = &self.secret_binary {
            o.insert("SecretBinary".into(), v.to_json());
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        if let Some(v) = &self.secret_string {
            o.insert("SecretString".into(), v.to_json());
        }
        if !self.version_stages.is_empty() {
            o.insert("VersionStages".into(), self.version_stages.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PutSecretValueResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
    pub version_id: Option<String>,
    pub version_stages: Vec<String>,
}

impl FromJson for PutSecretValueResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
            version_id: member(o, "VersionId", path)?,
            version_stages: member(o, "VersionStages", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for PutSecretValueResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        if !self.version_stages.is_empty() {
            o.insert("VersionStages".into(), self.version_stages.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RemoveRegionsFromReplicationRequest {
    pub remove_replica_regions: Vec<String>,
    pub secret_id: String,
}

impl FromJson for RemoveRegionsFromReplicationRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            remove_replica_regions: member(o, "RemoveReplicaRegions", path)?
                .ok_or_else(|| AwsError::missing_parameter("RemoveReplicaRegions"))?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for RemoveRegionsFromReplicationRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.remove_replica_regions.is_empty() {
            o.insert(
                "RemoveReplicaRegions".into(),
                self.remove_replica_regions.to_json(),
            );
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RemoveRegionsFromReplicationResponse {
    pub arn: Option<String>,
    pub replication_status: Vec<ReplicationStatusType>,
}

impl FromJson for RemoveRegionsFromReplicationResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            replication_status: member(o, "ReplicationStatus", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for RemoveRegionsFromReplicationResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if !self.replication_status.is_empty() {
            o.insert(
                "ReplicationStatus".into(),
                self.replication_status.to_json(),
            );
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReplicaRegionType {
    pub kms_key_id: Option<String>,
    pub region: Option<String>,
}

impl FromJson for ReplicaRegionType {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            kms_key_id: member(o, "KmsKeyId", path)?,
            region: member(o, "Region", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ReplicaRegionType {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.kms_key_id {
            o.insert("KmsKeyId".into(), v.to_json());
        }
        if let Some(v) = &self.region {
            o.insert("Region".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReplicateSecretToRegionsRequest {
    pub add_replica_regions: Vec<ReplicaRegionType>,
    pub force_overwrite_replica_secret: Option<bool>,
    pub secret_id: String,
}

impl FromJson for ReplicateSecretToRegionsRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            add_replica_regions: member(o, "AddReplicaRegions", path)?
                .ok_or_else(|| AwsError::missing_parameter("AddReplicaRegions"))?,
            force_overwrite_replica_secret: member(o, "ForceOverwriteReplicaSecret", path)?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for ReplicateSecretToRegionsRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.add_replica_regions.is_empty() {
            o.insert(
                "AddReplicaRegions".into(),
                self.add_replica_regions.to_json(),
            );
        }
        if let Some(v) = &self.force_overwrite_replica_secret {
            o.insert("ForceOverwriteReplicaSecret".into(), v.to_json());
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReplicateSecretToRegionsResponse {
    pub arn: Option<String>,
    pub replication_status: Vec<ReplicationStatusType>,
}

impl FromJson for ReplicateSecretToRegionsResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            replication_status: member(o, "ReplicationStatus", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ReplicateSecretToRegionsResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if !self.replication_status.is_empty() {
            o.insert(
                "ReplicationStatus".into(),
                self.replication_status.to_json(),
            );
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReplicationStatusType {
    pub kms_key_id: Option<String>,
    pub last_accessed_date: Option<Timestamp>,
    pub region: Option<String>,
    pub status: Option<String>,
    pub status_message: Option<String>,
}

impl FromJson for ReplicationStatusType {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            kms_key_id: member(o, "KmsKeyId", path)?,
            last_accessed_date: member(o, "LastAccessedDate", path)?,
            region: member(o, "Region", path)?,
            status: member(o, "Status", path)?,
            status_message: member(o, "StatusMessage", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ReplicationStatusType {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.kms_key_id {
            o.insert("KmsKeyId".into(), v.to_json());
        }
        if let Some(v) = &self.last_accessed_date {
            o.insert("LastAccessedDate".into(), v.to_json());
        }
        if let Some(v) = &self.region {
            o.insert("Region".into(), v.to_json());
        }
        if let Some(v) = &self.status {
            o.insert("Status".into(), v.to_json());
        }
        if let Some(v) = &self.status_message {
            o.insert("StatusMessage".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RestoreSecretRequest {
    pub secret_id: String,
}

impl FromJson for RestoreSecretRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for RestoreSecretRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RestoreSecretResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
}

impl FromJson for RestoreSecretResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
        };
        Ok(s)
    }
}

impl ToJson for RestoreSecretResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RotateSecretRequest {
    pub client_request_token: Option<String>,
    pub external_secret_rotation_metadata: Vec<ExternalSecretRotationMetadataItem>,
    pub external_secret_rotation_role_arn: Option<String>,
    pub rotate_immediately: Option<bool>,
    pub rotation_lambda_arn: Option<String>,
    pub rotation_rules: Option<RotationRulesType>,
    pub secret_id: String,
}

impl FromJson for RotateSecretRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            client_request_token: member(o, "ClientRequestToken", path)?,
            external_secret_rotation_metadata: member(o, "ExternalSecretRotationMetadata", path)?
                .unwrap_or_default(),
            external_secret_rotation_role_arn: member(o, "ExternalSecretRotationRoleArn", path)?,
            rotate_immediately: member(o, "RotateImmediately", path)?,
            rotation_lambda_arn: member(o, "RotationLambdaARN", path)?,
            rotation_rules: member(o, "RotationRules", path)?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for RotateSecretRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.client_request_token {
            o.insert("ClientRequestToken".into(), v.to_json());
        }
        if !self.external_secret_rotation_metadata.is_empty() {
            o.insert(
                "ExternalSecretRotationMetadata".into(),
                self.external_secret_rotation_metadata.to_json(),
            );
        }
        if let Some(v) = &self.external_secret_rotation_role_arn {
            o.insert("ExternalSecretRotationRoleArn".into(), v.to_json());
        }
        if let Some(v) = &self.rotate_immediately {
            o.insert("RotateImmediately".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_lambda_arn {
            o.insert("RotationLambdaARN".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_rules {
            o.insert("RotationRules".into(), v.to_json());
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RotateSecretResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
    pub version_id: Option<String>,
}

impl FromJson for RotateSecretResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
            version_id: member(o, "VersionId", path)?,
        };
        Ok(s)
    }
}

impl ToJson for RotateSecretResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RotationRulesType {
    pub automatically_after_days: Option<i64>,
    pub duration: Option<String>,
    pub schedule_expression: Option<String>,
}

impl FromJson for RotationRulesType {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            automatically_after_days: member(o, "AutomaticallyAfterDays", path)?,
            duration: member(o, "Duration", path)?,
            schedule_expression: member(o, "ScheduleExpression", path)?,
        };
        Ok(s)
    }
}

impl ToJson for RotationRulesType {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.automatically_after_days {
            o.insert("AutomaticallyAfterDays".into(), v.to_json());
        }
        if let Some(v) = &self.duration {
            o.insert("Duration".into(), v.to_json());
        }
        if let Some(v) = &self.schedule_expression {
            o.insert("ScheduleExpression".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SecretListEntry {
    pub arn: Option<String>,
    pub created_date: Option<Timestamp>,
    pub deleted_date: Option<Timestamp>,
    pub description: Option<String>,
    pub external_secret_rotation_metadata: Vec<ExternalSecretRotationMetadataItem>,
    pub external_secret_rotation_role_arn: Option<String>,
    pub kms_key_id: Option<String>,
    pub last_accessed_date: Option<Timestamp>,
    pub last_changed_date: Option<Timestamp>,
    pub last_rotated_date: Option<Timestamp>,
    pub name: Option<String>,
    pub next_rotation_date: Option<Timestamp>,
    pub owning_service: Option<String>,
    pub primary_region: Option<String>,
    pub rotation_enabled: Option<bool>,
    pub rotation_lambda_arn: Option<String>,
    pub rotation_rules: Option<RotationRulesType>,
    pub secret_versions_to_stages: BTreeMap<String, Vec<String>>,
    pub tags: Vec<Tag>,
    pub r#type: Option<String>,
}

impl FromJson for SecretListEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            created_date: member(o, "CreatedDate", path)?,
            deleted_date: member(o, "DeletedDate", path)?,
            description: member(o, "Description", path)?,
            external_secret_rotation_metadata: member(o, "ExternalSecretRotationMetadata", path)?
                .unwrap_or_default(),
            external_secret_rotation_role_arn: member(o, "ExternalSecretRotationRoleArn", path)?,
            kms_key_id: member(o, "KmsKeyId", path)?,
            last_accessed_date: member(o, "LastAccessedDate", path)?,
            last_changed_date: member(o, "LastChangedDate", path)?,
            last_rotated_date: member(o, "LastRotatedDate", path)?,
            name: member(o, "Name", path)?,
            next_rotation_date: member(o, "NextRotationDate", path)?,
            owning_service: member(o, "OwningService", path)?,
            primary_region: member(o, "PrimaryRegion", path)?,
            rotation_enabled: member(o, "RotationEnabled", path)?,
            rotation_lambda_arn: member(o, "RotationLambdaARN", path)?,
            rotation_rules: member(o, "RotationRules", path)?,
            secret_versions_to_stages: member(o, "SecretVersionsToStages", path)?
                .unwrap_or_default(),
            tags: member(o, "Tags", path)?.unwrap_or_default(),
            r#type: member(o, "Type", path)?,
        };
        Ok(s)
    }
}

impl ToJson for SecretListEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.created_date {
            o.insert("CreatedDate".into(), v.to_json());
        }
        if let Some(v) = &self.deleted_date {
            o.insert("DeletedDate".into(), v.to_json());
        }
        if let Some(v) = &self.description {
            o.insert("Description".into(), v.to_json());
        }
        if !self.external_secret_rotation_metadata.is_empty() {
            o.insert(
                "ExternalSecretRotationMetadata".into(),
                self.external_secret_rotation_metadata.to_json(),
            );
        }
        if let Some(v) = &self.external_secret_rotation_role_arn {
            o.insert("ExternalSecretRotationRoleArn".into(), v.to_json());
        }
        if let Some(v) = &self.kms_key_id {
            o.insert("KmsKeyId".into(), v.to_json());
        }
        if let Some(v) = &self.last_accessed_date {
            o.insert("LastAccessedDate".into(), v.to_json());
        }
        if let Some(v) = &self.last_changed_date {
            o.insert("LastChangedDate".into(), v.to_json());
        }
        if let Some(v) = &self.last_rotated_date {
            o.insert("LastRotatedDate".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.next_rotation_date {
            o.insert("NextRotationDate".into(), v.to_json());
        }
        if let Some(v) = &self.owning_service {
            o.insert("OwningService".into(), v.to_json());
        }
        if let Some(v) = &self.primary_region {
            o.insert("PrimaryRegion".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_enabled {
            o.insert("RotationEnabled".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_lambda_arn {
            o.insert("RotationLambdaARN".into(), v.to_json());
        }
        if let Some(v) = &self.rotation_rules {
            o.insert("RotationRules".into(), v.to_json());
        }
        if !self.secret_versions_to_stages.is_empty() {
            o.insert(
                "SecretVersionsToStages".into(),
                self.secret_versions_to_stages.to_json(),
            );
        }
        o.insert("Tags".into(), self.tags.to_json());
        if let Some(v) = &self.r#type {
            o.insert("Type".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SecretValueEntry {
    pub arn: Option<String>,
    pub created_date: Option<Timestamp>,
    pub name: Option<String>,
    pub secret_binary: Option<Blob>,
    pub secret_string: Option<String>,
    pub version_id: Option<String>,
    pub version_stages: Vec<String>,
}

impl FromJson for SecretValueEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            created_date: member(o, "CreatedDate", path)?,
            name: member(o, "Name", path)?,
            secret_binary: member(o, "SecretBinary", path)?,
            secret_string: member(o, "SecretString", path)?,
            version_id: member(o, "VersionId", path)?,
            version_stages: member(o, "VersionStages", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for SecretValueEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.created_date {
            o.insert("CreatedDate".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.secret_binary {
            o.insert("SecretBinary".into(), v.to_json());
        }
        if let Some(v) = &self.secret_string {
            o.insert("SecretString".into(), v.to_json());
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        if !self.version_stages.is_empty() {
            o.insert("VersionStages".into(), self.version_stages.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SecretVersionsListEntry {
    pub created_date: Option<Timestamp>,
    pub kms_key_ids: Vec<String>,
    pub last_accessed_date: Option<Timestamp>,
    pub version_id: Option<String>,
    pub version_stages: Vec<String>,
}

impl FromJson for SecretVersionsListEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            created_date: member(o, "CreatedDate", path)?,
            kms_key_ids: member(o, "KmsKeyIds", path)?.unwrap_or_default(),
            last_accessed_date: member(o, "LastAccessedDate", path)?,
            version_id: member(o, "VersionId", path)?,
            version_stages: member(o, "VersionStages", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for SecretVersionsListEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.created_date {
            o.insert("CreatedDate".into(), v.to_json());
        }
        if !self.kms_key_ids.is_empty() {
            o.insert("KmsKeyIds".into(), self.kms_key_ids.to_json());
        }
        if let Some(v) = &self.last_accessed_date {
            o.insert("LastAccessedDate".into(), v.to_json());
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        if !self.version_stages.is_empty() {
            o.insert("VersionStages".into(), self.version_stages.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct StopReplicationToReplicaRequest {
    pub secret_id: String,
}

impl FromJson for StopReplicationToReplicaRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
        };
        Ok(s)
    }
}

impl ToJson for StopReplicationToReplicaRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct StopReplicationToReplicaResponse {
    pub arn: Option<String>,
}

impl FromJson for StopReplicationToReplicaResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
        };
        Ok(s)
    }
}

impl ToJson for StopReplicationToReplicaResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Tag {
    pub key: Option<String>,
    pub value: Option<String>,
}

impl FromJson for Tag {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            key: member(o, "Key", path)?,
            value: member(o, "Value", path)?,
        };
        Ok(s)
    }
}

impl ToJson for Tag {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.key {
            o.insert("Key".into(), v.to_json());
        }
        if let Some(v) = &self.value {
            o.insert("Value".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TagResourceRequest {
    pub secret_id: String,
    pub tags: Vec<Tag>,
}

impl FromJson for TagResourceRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
            tags: member(o, "Tags", path)?.ok_or_else(|| AwsError::missing_parameter("Tags"))?,
        };
        Ok(s)
    }
}

impl ToJson for TagResourceRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        if !self.tags.is_empty() {
            o.insert("Tags".into(), self.tags.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UntagResourceRequest {
    pub secret_id: String,
    pub tag_keys: Vec<String>,
}

impl FromJson for UntagResourceRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
            tag_keys: member(o, "TagKeys", path)?
                .ok_or_else(|| AwsError::missing_parameter("TagKeys"))?,
        };
        Ok(s)
    }
}

impl ToJson for UntagResourceRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("SecretId".into(), self.secret_id.to_json());
        if !self.tag_keys.is_empty() {
            o.insert("TagKeys".into(), self.tag_keys.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UpdateSecretRequest {
    pub client_request_token: Option<String>,
    pub description: Option<String>,
    pub kms_key_id: Option<String>,
    pub secret_binary: Option<Blob>,
    pub secret_id: String,
    pub secret_string: Option<String>,
    pub r#type: Option<String>,
}

impl FromJson for UpdateSecretRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            client_request_token: member(o, "ClientRequestToken", path)?,
            description: member(o, "Description", path)?,
            kms_key_id: member(o, "KmsKeyId", path)?,
            secret_binary: member(o, "SecretBinary", path)?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
            secret_string: member(o, "SecretString", path)?,
            r#type: member(o, "Type", path)?,
        };
        Ok(s)
    }
}

impl ToJson for UpdateSecretRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.client_request_token {
            o.insert("ClientRequestToken".into(), v.to_json());
        }
        if let Some(v) = &self.description {
            o.insert("Description".into(), v.to_json());
        }
        if let Some(v) = &self.kms_key_id {
            o.insert("KmsKeyId".into(), v.to_json());
        }
        if let Some(v) = &self.secret_binary {
            o.insert("SecretBinary".into(), v.to_json());
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        if let Some(v) = &self.secret_string {
            o.insert("SecretString".into(), v.to_json());
        }
        if let Some(v) = &self.r#type {
            o.insert("Type".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UpdateSecretResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
    pub version_id: Option<String>,
}

impl FromJson for UpdateSecretResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
            version_id: member(o, "VersionId", path)?,
        };
        Ok(s)
    }
}

impl ToJson for UpdateSecretResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        if let Some(v) = &self.version_id {
            o.insert("VersionId".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UpdateSecretVersionStageRequest {
    pub move_to_version_id: Option<String>,
    pub remove_from_version_id: Option<String>,
    pub secret_id: String,
    pub version_stage: String,
}

impl FromJson for UpdateSecretVersionStageRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            move_to_version_id: member(o, "MoveToVersionId", path)?,
            remove_from_version_id: member(o, "RemoveFromVersionId", path)?,
            secret_id: member(o, "SecretId", path)?
                .ok_or_else(|| AwsError::missing_parameter("SecretId"))?,
            version_stage: member(o, "VersionStage", path)?
                .ok_or_else(|| AwsError::missing_parameter("VersionStage"))?,
        };
        Ok(s)
    }
}

impl ToJson for UpdateSecretVersionStageRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.move_to_version_id {
            o.insert("MoveToVersionId".into(), v.to_json());
        }
        if let Some(v) = &self.remove_from_version_id {
            o.insert("RemoveFromVersionId".into(), v.to_json());
        }
        o.insert("SecretId".into(), self.secret_id.to_json());
        o.insert("VersionStage".into(), self.version_stage.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UpdateSecretVersionStageResponse {
    pub arn: Option<String>,
    pub name: Option<String>,
}

impl FromJson for UpdateSecretVersionStageResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            arn: member(o, "ARN", path)?,
            name: member(o, "Name", path)?,
        };
        Ok(s)
    }
}

impl ToJson for UpdateSecretVersionStageResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.arn {
            o.insert("ARN".into(), v.to_json());
        }
        if let Some(v) = &self.name {
            o.insert("Name".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ValidateResourcePolicyRequest {
    pub resource_policy: String,
    pub secret_id: Option<String>,
}

impl FromJson for ValidateResourcePolicyRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            resource_policy: member(o, "ResourcePolicy", path)?
                .ok_or_else(|| AwsError::missing_parameter("ResourcePolicy"))?,
            secret_id: member(o, "SecretId", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ValidateResourcePolicyRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("ResourcePolicy".into(), self.resource_policy.to_json());
        if let Some(v) = &self.secret_id {
            o.insert("SecretId".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ValidateResourcePolicyResponse {
    pub policy_validation_passed: Option<bool>,
    pub validation_errors: Vec<ValidationErrorsEntry>,
}

impl FromJson for ValidateResourcePolicyResponse {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            policy_validation_passed: member(o, "PolicyValidationPassed", path)?,
            validation_errors: member(o, "ValidationErrors", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ValidateResourcePolicyResponse {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.policy_validation_passed {
            o.insert("PolicyValidationPassed".into(), v.to_json());
        }
        if !self.validation_errors.is_empty() {
            o.insert("ValidationErrors".into(), self.validation_errors.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ValidationErrorsEntry {
    pub check_name: Option<String>,
    pub error_message: Option<String>,
}

impl FromJson for ValidationErrorsEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            check_name: member(o, "CheckName", path)?,
            error_message: member(o, "ErrorMessage", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ValidationErrorsEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.check_name {
            o.insert("CheckName".into(), v.to_json());
        }
        if let Some(v) = &self.error_message {
            o.insert("ErrorMessage".into(), v.to_json());
        }
        Value::Object(o)
    }
}

/// Implement the operations you support; the rest answer `NotImplemented`.
pub trait Service: Send + Sync {
    fn batch_get_secret_value(
        &self,
        ctx: &RequestContext,
        input: BatchGetSecretValueRequest,
    ) -> Result<BatchGetSecretValueResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "BatchGetSecretValue",
        ))
    }
    fn cancel_rotate_secret(
        &self,
        ctx: &RequestContext,
        input: CancelRotateSecretRequest,
    ) -> Result<CancelRotateSecretResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "CancelRotateSecret",
        ))
    }
    fn create_secret(
        &self,
        ctx: &RequestContext,
        input: CreateSecretRequest,
    ) -> Result<CreateSecretResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "CreateSecret"))
    }
    fn delete_resource_policy(
        &self,
        ctx: &RequestContext,
        input: DeleteResourcePolicyRequest,
    ) -> Result<DeleteResourcePolicyResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "DeleteResourcePolicy",
        ))
    }
    fn delete_secret(
        &self,
        ctx: &RequestContext,
        input: DeleteSecretRequest,
    ) -> Result<DeleteSecretResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "DeleteSecret"))
    }
    fn describe_secret(
        &self,
        ctx: &RequestContext,
        input: DescribeSecretRequest,
    ) -> Result<DescribeSecretResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "DescribeSecret",
        ))
    }
    fn get_random_password(
        &self,
        ctx: &RequestContext,
        input: GetRandomPasswordRequest,
    ) -> Result<GetRandomPasswordResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "GetRandomPassword",
        ))
    }
    fn get_resource_policy(
        &self,
        ctx: &RequestContext,
        input: GetResourcePolicyRequest,
    ) -> Result<GetResourcePolicyResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "GetResourcePolicy",
        ))
    }
    fn get_secret_value(
        &self,
        ctx: &RequestContext,
        input: GetSecretValueRequest,
    ) -> Result<GetSecretValueResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "GetSecretValue",
        ))
    }
    fn list_secret_version_ids(
        &self,
        ctx: &RequestContext,
        input: ListSecretVersionIdsRequest,
    ) -> Result<ListSecretVersionIdsResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "ListSecretVersionIds",
        ))
    }
    fn list_secrets(
        &self,
        ctx: &RequestContext,
        input: ListSecretsRequest,
    ) -> Result<ListSecretsResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "ListSecrets"))
    }
    fn put_resource_policy(
        &self,
        ctx: &RequestContext,
        input: PutResourcePolicyRequest,
    ) -> Result<PutResourcePolicyResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "PutResourcePolicy",
        ))
    }
    fn put_secret_value(
        &self,
        ctx: &RequestContext,
        input: PutSecretValueRequest,
    ) -> Result<PutSecretValueResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "PutSecretValue",
        ))
    }
    fn remove_regions_from_replication(
        &self,
        ctx: &RequestContext,
        input: RemoveRegionsFromReplicationRequest,
    ) -> Result<RemoveRegionsFromReplicationResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "RemoveRegionsFromReplication",
        ))
    }
    fn replicate_secret_to_regions(
        &self,
        ctx: &RequestContext,
        input: ReplicateSecretToRegionsRequest,
    ) -> Result<ReplicateSecretToRegionsResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "ReplicateSecretToRegions",
        ))
    }
    fn restore_secret(
        &self,
        ctx: &RequestContext,
        input: RestoreSecretRequest,
    ) -> Result<RestoreSecretResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "RestoreSecret"))
    }
    fn rotate_secret(
        &self,
        ctx: &RequestContext,
        input: RotateSecretRequest,
    ) -> Result<RotateSecretResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "RotateSecret"))
    }
    fn stop_replication_to_replica(
        &self,
        ctx: &RequestContext,
        input: StopReplicationToReplicaRequest,
    ) -> Result<StopReplicationToReplicaResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "StopReplicationToReplica",
        ))
    }
    fn tag_resource(
        &self,
        ctx: &RequestContext,
        input: TagResourceRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "TagResource"))
    }
    fn untag_resource(
        &self,
        ctx: &RequestContext,
        input: UntagResourceRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "UntagResource"))
    }
    fn update_secret(
        &self,
        ctx: &RequestContext,
        input: UpdateSecretRequest,
    ) -> Result<UpdateSecretResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("secretsmanager", "UpdateSecret"))
    }
    fn update_secret_version_stage(
        &self,
        ctx: &RequestContext,
        input: UpdateSecretVersionStageRequest,
    ) -> Result<UpdateSecretVersionStageResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "UpdateSecretVersionStage",
        ))
    }
    fn validate_resource_policy(
        &self,
        ctx: &RequestContext,
        input: ValidateResourcePolicyRequest,
    ) -> Result<ValidateResourcePolicyResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "secretsmanager",
            "ValidateResourcePolicy",
        ))
    }
}

pub fn dispatch<S: Service + ?Sized>(
    svc: &S,
    ctx: &RequestContext,
    operation: &str,
    body: &Value,
) -> Result<RawResponse, AwsError> {
    match operation {
        "BatchGetSecretValue" => {
            let output =
                svc.batch_get_secret_value(ctx, BatchGetSecretValueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "CancelRotateSecret" => {
            let output =
                svc.cancel_rotate_secret(ctx, CancelRotateSecretRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "CreateSecret" => {
            let output = svc.create_secret(ctx, CreateSecretRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "DeleteResourcePolicy" => {
            let output =
                svc.delete_resource_policy(ctx, DeleteResourcePolicyRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "DeleteSecret" => {
            let output = svc.delete_secret(ctx, DeleteSecretRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "DescribeSecret" => {
            let output = svc.describe_secret(ctx, DescribeSecretRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "GetRandomPassword" => {
            let output =
                svc.get_random_password(ctx, GetRandomPasswordRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "GetResourcePolicy" => {
            let output =
                svc.get_resource_policy(ctx, GetResourcePolicyRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "GetSecretValue" => {
            let output = svc.get_secret_value(ctx, GetSecretValueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ListSecretVersionIds" => {
            let output = svc
                .list_secret_version_ids(ctx, ListSecretVersionIdsRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ListSecrets" => {
            let output = svc.list_secrets(ctx, ListSecretsRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "PutResourcePolicy" => {
            let output =
                svc.put_resource_policy(ctx, PutResourcePolicyRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "PutSecretValue" => {
            let output = svc.put_secret_value(ctx, PutSecretValueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "RemoveRegionsFromReplication" => {
            let output = svc.remove_regions_from_replication(
                ctx,
                RemoveRegionsFromReplicationRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ReplicateSecretToRegions" => {
            let output = svc.replicate_secret_to_regions(
                ctx,
                ReplicateSecretToRegionsRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "RestoreSecret" => {
            let output = svc.restore_secret(ctx, RestoreSecretRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "RotateSecret" => {
            let output = svc.rotate_secret(ctx, RotateSecretRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "StopReplicationToReplica" => {
            let output = svc.stop_replication_to_replica(
                ctx,
                StopReplicationToReplicaRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "TagResource" => {
            let output = svc.tag_resource(ctx, TagResourceRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "UntagResource" => {
            let output = svc.untag_resource(ctx, UntagResourceRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "UpdateSecret" => {
            let output = svc.update_secret(ctx, UpdateSecretRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "UpdateSecretVersionStage" => {
            let output = svc.update_secret_version_stage(
                ctx,
                UpdateSecretVersionStageRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ValidateResourcePolicy" => {
            let output = svc.validate_resource_policy(
                ctx,
                ValidateResourcePolicyRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        other => Err(AwsError::invalid_action(other)),
    }
}
