diesel::table! { secrets (account_id, region, name) {
account_id -> Text,
region -> Text,
name -> Text,
arn -> Text,
description -> Nullable<Text>,
kms_key_id -> Nullable<Text>,
created_at -> BigInt,
changed_at -> BigInt,
accessed_at -> Nullable<BigInt>,
deleted_at -> Nullable<BigInt>,
tags -> Text,
policy -> Nullable<Text>,
rotation_enabled -> BigInt,
rotation_lambda_arn -> Nullable<Text>,
rotation_rules -> Nullable<Text>,
last_rotated_at -> Nullable<BigInt>,
}}
diesel::table! { secret_versions (seq) {
seq -> BigInt,
account_id -> Text,
region -> Text,
secret_name -> Text,
version_id -> Text,
secret_string -> Nullable<Text>,
secret_binary -> Nullable<Binary>,
stages -> Text,
created_at -> BigInt,
}}
