// @generated by roto-codegen from the botocore model. DO NOT EDIT.
#![allow(clippy::all, dead_code, unused_variables, unused_mut, unused_imports)]

use roto_core::{AwsError, RawResponse, RequestContext};
use roto_protocol::json::{as_object, member};
use roto_protocol::{Blob, FromJson, Timestamp, ToJson, json_response};
use serde_json::{Map, Value};
use std::collections::BTreeMap;

pub const JSON_VERSION: &str = "1.0";
pub const TARGET_PREFIX: &str = "AmazonSQS";
pub const QUERY_COMPATIBLE: bool = true;
pub const API_VERSION: &str = "2012-11-05";

/// (operation, supported by the generated codec)
pub const OPERATIONS: &[(&str, bool)] = &[
    ("AddPermission", true),
    ("CancelMessageMoveTask", true),
    ("ChangeMessageVisibility", true),
    ("ChangeMessageVisibilityBatch", true),
    ("CreateQueue", true),
    ("DeleteMessage", true),
    ("DeleteMessageBatch", true),
    ("DeleteQueue", true),
    ("GetQueueAttributes", true),
    ("GetQueueUrl", true),
    ("ListDeadLetterSourceQueues", true),
    ("ListMessageMoveTasks", true),
    ("ListQueueTags", true),
    ("ListQueues", true),
    ("PurgeQueue", true),
    ("ReceiveMessage", true),
    ("RemovePermission", true),
    ("SendMessage", true),
    ("SendMessageBatch", true),
    ("SetQueueAttributes", true),
    ("StartMessageMoveTask", true),
    ("TagQueue", true),
    ("UntagQueue", true),
];

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AddPermissionRequest {
    pub aws_account_ids: Vec<String>,
    pub actions: Vec<String>,
    pub label: String,
    pub queue_url: String,
}

impl FromJson for AddPermissionRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            aws_account_ids: member(o, "AWSAccountIds", path)?
                .ok_or_else(|| AwsError::missing_parameter("AWSAccountIds"))?,
            actions: member(o, "Actions", path)?
                .ok_or_else(|| AwsError::missing_parameter("Actions"))?,
            label: member(o, "Label", path)?.ok_or_else(|| AwsError::missing_parameter("Label"))?,
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for AddPermissionRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.aws_account_ids.is_empty() {
            o.insert("AWSAccountIds".into(), self.aws_account_ids.to_json());
        }
        if !self.actions.is_empty() {
            o.insert("Actions".into(), self.actions.to_json());
        }
        o.insert("Label".into(), self.label.to_json());
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BatchResultErrorEntry {
    pub code: String,
    pub id: String,
    pub message: Option<String>,
    pub sender_fault: bool,
}

impl FromJson for BatchResultErrorEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            code: member(o, "Code", path)?.ok_or_else(|| AwsError::missing_parameter("Code"))?,
            id: member(o, "Id", path)?.ok_or_else(|| AwsError::missing_parameter("Id"))?,
            message: member(o, "Message", path)?,
            sender_fault: member(o, "SenderFault", path)?
                .ok_or_else(|| AwsError::missing_parameter("SenderFault"))?,
        };
        Ok(s)
    }
}

impl ToJson for BatchResultErrorEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("Code".into(), self.code.to_json());
        o.insert("Id".into(), self.id.to_json());
        if let Some(v) = &self.message {
            o.insert("Message".into(), v.to_json());
        }
        o.insert("SenderFault".into(), self.sender_fault.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CancelMessageMoveTaskRequest {
    pub task_handle: String,
}

impl FromJson for CancelMessageMoveTaskRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            task_handle: member(o, "TaskHandle", path)?
                .ok_or_else(|| AwsError::missing_parameter("TaskHandle"))?,
        };
        Ok(s)
    }
}

impl ToJson for CancelMessageMoveTaskRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("TaskHandle".into(), self.task_handle.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CancelMessageMoveTaskResult {
    pub approximate_number_of_messages_moved: Option<i64>,
}

impl FromJson for CancelMessageMoveTaskResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            approximate_number_of_messages_moved: member(
                o,
                "ApproximateNumberOfMessagesMoved",
                path,
            )?,
        };
        Ok(s)
    }
}

impl ToJson for CancelMessageMoveTaskResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.approximate_number_of_messages_moved {
            o.insert("ApproximateNumberOfMessagesMoved".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChangeMessageVisibilityBatchRequest {
    pub entries: Vec<ChangeMessageVisibilityBatchRequestEntry>,
    pub queue_url: String,
}

impl FromJson for ChangeMessageVisibilityBatchRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            entries: member(o, "Entries", path)?
                .ok_or_else(|| AwsError::missing_parameter("Entries"))?,
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for ChangeMessageVisibilityBatchRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.entries.is_empty() {
            o.insert("Entries".into(), self.entries.to_json());
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChangeMessageVisibilityBatchRequestEntry {
    pub id: String,
    pub receipt_handle: String,
    pub visibility_timeout: Option<i32>,
}

impl FromJson for ChangeMessageVisibilityBatchRequestEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            id: member(o, "Id", path)?.ok_or_else(|| AwsError::missing_parameter("Id"))?,
            receipt_handle: member(o, "ReceiptHandle", path)?
                .ok_or_else(|| AwsError::missing_parameter("ReceiptHandle"))?,
            visibility_timeout: member(o, "VisibilityTimeout", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ChangeMessageVisibilityBatchRequestEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("Id".into(), self.id.to_json());
        o.insert("ReceiptHandle".into(), self.receipt_handle.to_json());
        if let Some(v) = &self.visibility_timeout {
            o.insert("VisibilityTimeout".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChangeMessageVisibilityBatchResult {
    pub failed: Vec<BatchResultErrorEntry>,
    pub successful: Vec<ChangeMessageVisibilityBatchResultEntry>,
}

impl FromJson for ChangeMessageVisibilityBatchResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            failed: member(o, "Failed", path)?
                .ok_or_else(|| AwsError::missing_parameter("Failed"))?,
            successful: member(o, "Successful", path)?
                .ok_or_else(|| AwsError::missing_parameter("Successful"))?,
        };
        Ok(s)
    }
}

impl ToJson for ChangeMessageVisibilityBatchResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.failed.is_empty() {
            o.insert("Failed".into(), self.failed.to_json());
        }
        if !self.successful.is_empty() {
            o.insert("Successful".into(), self.successful.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChangeMessageVisibilityBatchResultEntry {
    pub id: String,
}

impl FromJson for ChangeMessageVisibilityBatchResultEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            id: member(o, "Id", path)?.ok_or_else(|| AwsError::missing_parameter("Id"))?,
        };
        Ok(s)
    }
}

impl ToJson for ChangeMessageVisibilityBatchResultEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("Id".into(), self.id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChangeMessageVisibilityRequest {
    pub queue_url: String,
    pub receipt_handle: String,
    pub visibility_timeout: i32,
}

impl FromJson for ChangeMessageVisibilityRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
            receipt_handle: member(o, "ReceiptHandle", path)?
                .ok_or_else(|| AwsError::missing_parameter("ReceiptHandle"))?,
            visibility_timeout: member(o, "VisibilityTimeout", path)?
                .ok_or_else(|| AwsError::missing_parameter("VisibilityTimeout"))?,
        };
        Ok(s)
    }
}

impl ToJson for ChangeMessageVisibilityRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        o.insert("ReceiptHandle".into(), self.receipt_handle.to_json());
        o.insert(
            "VisibilityTimeout".into(),
            self.visibility_timeout.to_json(),
        );
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CreateQueueRequest {
    pub attributes: BTreeMap<String, String>,
    pub queue_name: String,
    pub tags: BTreeMap<String, String>,
}

impl FromJson for CreateQueueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            attributes: member(o, "Attributes", path)?.unwrap_or_default(),
            queue_name: member(o, "QueueName", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueName"))?,
            tags: member(o, "tags", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for CreateQueueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.attributes.is_empty() {
            o.insert("Attributes".into(), self.attributes.to_json());
        }
        o.insert("QueueName".into(), self.queue_name.to_json());
        if !self.tags.is_empty() {
            o.insert("tags".into(), self.tags.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CreateQueueResult {
    pub queue_url: Option<String>,
}

impl FromJson for CreateQueueResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?,
        };
        Ok(s)
    }
}

impl ToJson for CreateQueueResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.queue_url {
            o.insert("QueueUrl".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteMessageBatchRequest {
    pub entries: Vec<DeleteMessageBatchRequestEntry>,
    pub queue_url: String,
}

impl FromJson for DeleteMessageBatchRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            entries: member(o, "Entries", path)?
                .ok_or_else(|| AwsError::missing_parameter("Entries"))?,
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteMessageBatchRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.entries.is_empty() {
            o.insert("Entries".into(), self.entries.to_json());
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteMessageBatchRequestEntry {
    pub id: String,
    pub receipt_handle: String,
}

impl FromJson for DeleteMessageBatchRequestEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            id: member(o, "Id", path)?.ok_or_else(|| AwsError::missing_parameter("Id"))?,
            receipt_handle: member(o, "ReceiptHandle", path)?
                .ok_or_else(|| AwsError::missing_parameter("ReceiptHandle"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteMessageBatchRequestEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("Id".into(), self.id.to_json());
        o.insert("ReceiptHandle".into(), self.receipt_handle.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteMessageBatchResult {
    pub failed: Vec<BatchResultErrorEntry>,
    pub successful: Vec<DeleteMessageBatchResultEntry>,
}

impl FromJson for DeleteMessageBatchResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            failed: member(o, "Failed", path)?
                .ok_or_else(|| AwsError::missing_parameter("Failed"))?,
            successful: member(o, "Successful", path)?
                .ok_or_else(|| AwsError::missing_parameter("Successful"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteMessageBatchResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.failed.is_empty() {
            o.insert("Failed".into(), self.failed.to_json());
        }
        if !self.successful.is_empty() {
            o.insert("Successful".into(), self.successful.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteMessageBatchResultEntry {
    pub id: String,
}

impl FromJson for DeleteMessageBatchResultEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            id: member(o, "Id", path)?.ok_or_else(|| AwsError::missing_parameter("Id"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteMessageBatchResultEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("Id".into(), self.id.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteMessageRequest {
    pub queue_url: String,
    pub receipt_handle: String,
}

impl FromJson for DeleteMessageRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
            receipt_handle: member(o, "ReceiptHandle", path)?
                .ok_or_else(|| AwsError::missing_parameter("ReceiptHandle"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteMessageRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        o.insert("ReceiptHandle".into(), self.receipt_handle.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DeleteQueueRequest {
    pub queue_url: String,
}

impl FromJson for DeleteQueueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for DeleteQueueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetQueueAttributesRequest {
    pub attribute_names: Vec<String>,
    pub queue_url: String,
}

impl FromJson for GetQueueAttributesRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            attribute_names: member(o, "AttributeNames", path)?.unwrap_or_default(),
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for GetQueueAttributesRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.attribute_names.is_empty() {
            o.insert("AttributeNames".into(), self.attribute_names.to_json());
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetQueueAttributesResult {
    pub attributes: BTreeMap<String, String>,
}

impl FromJson for GetQueueAttributesResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            attributes: member(o, "Attributes", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for GetQueueAttributesResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.attributes.is_empty() {
            o.insert("Attributes".into(), self.attributes.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetQueueUrlRequest {
    pub queue_name: String,
    pub queue_owner_aws_account_id: Option<String>,
}

impl FromJson for GetQueueUrlRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_name: member(o, "QueueName", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueName"))?,
            queue_owner_aws_account_id: member(o, "QueueOwnerAWSAccountId", path)?,
        };
        Ok(s)
    }
}

impl ToJson for GetQueueUrlRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueName".into(), self.queue_name.to_json());
        if let Some(v) = &self.queue_owner_aws_account_id {
            o.insert("QueueOwnerAWSAccountId".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetQueueUrlResult {
    pub queue_url: Option<String>,
}

impl FromJson for GetQueueUrlResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?,
        };
        Ok(s)
    }
}

impl ToJson for GetQueueUrlResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.queue_url {
            o.insert("QueueUrl".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListDeadLetterSourceQueuesRequest {
    pub max_results: Option<i32>,
    pub next_token: Option<String>,
    pub queue_url: String,
}

impl FromJson for ListDeadLetterSourceQueuesRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            max_results: member(o, "MaxResults", path)?,
            next_token: member(o, "NextToken", path)?,
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for ListDeadLetterSourceQueuesRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.max_results {
            o.insert("MaxResults".into(), v.to_json());
        }
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListDeadLetterSourceQueuesResult {
    pub next_token: Option<String>,
    pub queue_urls: Vec<String>,
}

impl FromJson for ListDeadLetterSourceQueuesResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            next_token: member(o, "NextToken", path)?,
            queue_urls: member(o, "queueUrls", path)?
                .ok_or_else(|| AwsError::missing_parameter("queueUrls"))?,
        };
        Ok(s)
    }
}

impl ToJson for ListDeadLetterSourceQueuesResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        if !self.queue_urls.is_empty() {
            o.insert("queueUrls".into(), self.queue_urls.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListMessageMoveTasksRequest {
    pub max_results: Option<i32>,
    pub source_arn: String,
}

impl FromJson for ListMessageMoveTasksRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            max_results: member(o, "MaxResults", path)?,
            source_arn: member(o, "SourceArn", path)?
                .ok_or_else(|| AwsError::missing_parameter("SourceArn"))?,
        };
        Ok(s)
    }
}

impl ToJson for ListMessageMoveTasksRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.max_results {
            o.insert("MaxResults".into(), v.to_json());
        }
        o.insert("SourceArn".into(), self.source_arn.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListMessageMoveTasksResult {
    pub results: Vec<ListMessageMoveTasksResultEntry>,
}

impl FromJson for ListMessageMoveTasksResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            results: member(o, "Results", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ListMessageMoveTasksResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.results.is_empty() {
            o.insert("Results".into(), self.results.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListMessageMoveTasksResultEntry {
    pub approximate_number_of_messages_moved: Option<i64>,
    pub approximate_number_of_messages_to_move: Option<i64>,
    pub destination_arn: Option<String>,
    pub failure_reason: Option<String>,
    pub max_number_of_messages_per_second: Option<i32>,
    pub source_arn: Option<String>,
    pub started_timestamp: Option<i64>,
    pub status: Option<String>,
    pub task_handle: Option<String>,
}

impl FromJson for ListMessageMoveTasksResultEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            approximate_number_of_messages_moved: member(
                o,
                "ApproximateNumberOfMessagesMoved",
                path,
            )?,
            approximate_number_of_messages_to_move: member(
                o,
                "ApproximateNumberOfMessagesToMove",
                path,
            )?,
            destination_arn: member(o, "DestinationArn", path)?,
            failure_reason: member(o, "FailureReason", path)?,
            max_number_of_messages_per_second: member(o, "MaxNumberOfMessagesPerSecond", path)?,
            source_arn: member(o, "SourceArn", path)?,
            started_timestamp: member(o, "StartedTimestamp", path)?,
            status: member(o, "Status", path)?,
            task_handle: member(o, "TaskHandle", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ListMessageMoveTasksResultEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.approximate_number_of_messages_moved {
            o.insert("ApproximateNumberOfMessagesMoved".into(), v.to_json());
        }
        if let Some(v) = &self.approximate_number_of_messages_to_move {
            o.insert("ApproximateNumberOfMessagesToMove".into(), v.to_json());
        }
        if let Some(v) = &self.destination_arn {
            o.insert("DestinationArn".into(), v.to_json());
        }
        if let Some(v) = &self.failure_reason {
            o.insert("FailureReason".into(), v.to_json());
        }
        if let Some(v) = &self.max_number_of_messages_per_second {
            o.insert("MaxNumberOfMessagesPerSecond".into(), v.to_json());
        }
        if let Some(v) = &self.source_arn {
            o.insert("SourceArn".into(), v.to_json());
        }
        if let Some(v) = &self.started_timestamp {
            o.insert("StartedTimestamp".into(), v.to_json());
        }
        if let Some(v) = &self.status {
            o.insert("Status".into(), v.to_json());
        }
        if let Some(v) = &self.task_handle {
            o.insert("TaskHandle".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListQueueTagsRequest {
    pub queue_url: String,
}

impl FromJson for ListQueueTagsRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for ListQueueTagsRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListQueueTagsResult {
    pub tags: BTreeMap<String, String>,
}

impl FromJson for ListQueueTagsResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            tags: member(o, "Tags", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ListQueueTagsResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.tags.is_empty() {
            o.insert("Tags".into(), self.tags.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListQueuesRequest {
    pub max_results: Option<i32>,
    pub next_token: Option<String>,
    pub queue_name_prefix: Option<String>,
}

impl FromJson for ListQueuesRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            max_results: member(o, "MaxResults", path)?,
            next_token: member(o, "NextToken", path)?,
            queue_name_prefix: member(o, "QueueNamePrefix", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ListQueuesRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.max_results {
            o.insert("MaxResults".into(), v.to_json());
        }
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        if let Some(v) = &self.queue_name_prefix {
            o.insert("QueueNamePrefix".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListQueuesResult {
    pub next_token: Option<String>,
    pub queue_urls: Vec<String>,
}

impl FromJson for ListQueuesResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            next_token: member(o, "NextToken", path)?,
            queue_urls: member(o, "QueueUrls", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ListQueuesResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.next_token {
            o.insert("NextToken".into(), v.to_json());
        }
        if !self.queue_urls.is_empty() {
            o.insert("QueueUrls".into(), self.queue_urls.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Message {
    pub attributes: BTreeMap<String, String>,
    pub body: Option<String>,
    pub md5_of_body: Option<String>,
    pub md5_of_message_attributes: Option<String>,
    pub message_attributes: BTreeMap<String, MessageAttributeValue>,
    pub message_id: Option<String>,
    pub receipt_handle: Option<String>,
}

impl FromJson for Message {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            attributes: member(o, "Attributes", path)?.unwrap_or_default(),
            body: member(o, "Body", path)?,
            md5_of_body: member(o, "MD5OfBody", path)?,
            md5_of_message_attributes: member(o, "MD5OfMessageAttributes", path)?,
            message_attributes: member(o, "MessageAttributes", path)?.unwrap_or_default(),
            message_id: member(o, "MessageId", path)?,
            receipt_handle: member(o, "ReceiptHandle", path)?,
        };
        Ok(s)
    }
}

impl ToJson for Message {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.attributes.is_empty() {
            o.insert("Attributes".into(), self.attributes.to_json());
        }
        if let Some(v) = &self.body {
            o.insert("Body".into(), v.to_json());
        }
        if let Some(v) = &self.md5_of_body {
            o.insert("MD5OfBody".into(), v.to_json());
        }
        if let Some(v) = &self.md5_of_message_attributes {
            o.insert("MD5OfMessageAttributes".into(), v.to_json());
        }
        if !self.message_attributes.is_empty() {
            o.insert(
                "MessageAttributes".into(),
                self.message_attributes.to_json(),
            );
        }
        if let Some(v) = &self.message_id {
            o.insert("MessageId".into(), v.to_json());
        }
        if let Some(v) = &self.receipt_handle {
            o.insert("ReceiptHandle".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MessageAttributeValue {
    pub binary_list_values: Vec<Blob>,
    pub binary_value: Option<Blob>,
    pub data_type: String,
    pub string_list_values: Vec<String>,
    pub string_value: Option<String>,
}

impl FromJson for MessageAttributeValue {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            binary_list_values: member(o, "BinaryListValues", path)?.unwrap_or_default(),
            binary_value: member(o, "BinaryValue", path)?,
            data_type: member(o, "DataType", path)?
                .ok_or_else(|| AwsError::missing_parameter("DataType"))?,
            string_list_values: member(o, "StringListValues", path)?.unwrap_or_default(),
            string_value: member(o, "StringValue", path)?,
        };
        Ok(s)
    }
}

impl ToJson for MessageAttributeValue {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.binary_list_values.is_empty() {
            o.insert("BinaryListValues".into(), self.binary_list_values.to_json());
        }
        if let Some(v) = &self.binary_value {
            o.insert("BinaryValue".into(), v.to_json());
        }
        o.insert("DataType".into(), self.data_type.to_json());
        if !self.string_list_values.is_empty() {
            o.insert("StringListValues".into(), self.string_list_values.to_json());
        }
        if let Some(v) = &self.string_value {
            o.insert("StringValue".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MessageSystemAttributeValue {
    pub binary_list_values: Vec<Blob>,
    pub binary_value: Option<Blob>,
    pub data_type: String,
    pub string_list_values: Vec<String>,
    pub string_value: Option<String>,
}

impl FromJson for MessageSystemAttributeValue {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            binary_list_values: member(o, "BinaryListValues", path)?.unwrap_or_default(),
            binary_value: member(o, "BinaryValue", path)?,
            data_type: member(o, "DataType", path)?
                .ok_or_else(|| AwsError::missing_parameter("DataType"))?,
            string_list_values: member(o, "StringListValues", path)?.unwrap_or_default(),
            string_value: member(o, "StringValue", path)?,
        };
        Ok(s)
    }
}

impl ToJson for MessageSystemAttributeValue {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.binary_list_values.is_empty() {
            o.insert("BinaryListValues".into(), self.binary_list_values.to_json());
        }
        if let Some(v) = &self.binary_value {
            o.insert("BinaryValue".into(), v.to_json());
        }
        o.insert("DataType".into(), self.data_type.to_json());
        if !self.string_list_values.is_empty() {
            o.insert("StringListValues".into(), self.string_list_values.to_json());
        }
        if let Some(v) = &self.string_value {
            o.insert("StringValue".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PurgeQueueRequest {
    pub queue_url: String,
}

impl FromJson for PurgeQueueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for PurgeQueueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReceiveMessageRequest {
    pub attribute_names: Vec<String>,
    pub max_number_of_messages: Option<i32>,
    pub message_attribute_names: Vec<String>,
    pub message_system_attribute_names: Vec<String>,
    pub queue_url: String,
    pub receive_request_attempt_id: Option<String>,
    pub visibility_timeout: Option<i32>,
    pub wait_time_seconds: Option<i32>,
}

impl FromJson for ReceiveMessageRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            attribute_names: member(o, "AttributeNames", path)?.unwrap_or_default(),
            max_number_of_messages: member(o, "MaxNumberOfMessages", path)?,
            message_attribute_names: member(o, "MessageAttributeNames", path)?.unwrap_or_default(),
            message_system_attribute_names: member(o, "MessageSystemAttributeNames", path)?
                .unwrap_or_default(),
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
            receive_request_attempt_id: member(o, "ReceiveRequestAttemptId", path)?,
            visibility_timeout: member(o, "VisibilityTimeout", path)?,
            wait_time_seconds: member(o, "WaitTimeSeconds", path)?,
        };
        Ok(s)
    }
}

impl ToJson for ReceiveMessageRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.attribute_names.is_empty() {
            o.insert("AttributeNames".into(), self.attribute_names.to_json());
        }
        if let Some(v) = &self.max_number_of_messages {
            o.insert("MaxNumberOfMessages".into(), v.to_json());
        }
        if !self.message_attribute_names.is_empty() {
            o.insert(
                "MessageAttributeNames".into(),
                self.message_attribute_names.to_json(),
            );
        }
        if !self.message_system_attribute_names.is_empty() {
            o.insert(
                "MessageSystemAttributeNames".into(),
                self.message_system_attribute_names.to_json(),
            );
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        if let Some(v) = &self.receive_request_attempt_id {
            o.insert("ReceiveRequestAttemptId".into(), v.to_json());
        }
        if let Some(v) = &self.visibility_timeout {
            o.insert("VisibilityTimeout".into(), v.to_json());
        }
        if let Some(v) = &self.wait_time_seconds {
            o.insert("WaitTimeSeconds".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReceiveMessageResult {
    pub messages: Vec<Message>,
}

impl FromJson for ReceiveMessageResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            messages: member(o, "Messages", path)?.unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for ReceiveMessageResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.messages.is_empty() {
            o.insert("Messages".into(), self.messages.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RemovePermissionRequest {
    pub label: String,
    pub queue_url: String,
}

impl FromJson for RemovePermissionRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            label: member(o, "Label", path)?.ok_or_else(|| AwsError::missing_parameter("Label"))?,
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for RemovePermissionRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("Label".into(), self.label.to_json());
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SendMessageBatchRequest {
    pub entries: Vec<SendMessageBatchRequestEntry>,
    pub queue_url: String,
}

impl FromJson for SendMessageBatchRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            entries: member(o, "Entries", path)?
                .ok_or_else(|| AwsError::missing_parameter("Entries"))?,
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for SendMessageBatchRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.entries.is_empty() {
            o.insert("Entries".into(), self.entries.to_json());
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SendMessageBatchRequestEntry {
    pub delay_seconds: Option<i32>,
    pub id: String,
    pub message_attributes: BTreeMap<String, MessageAttributeValue>,
    pub message_body: String,
    pub message_deduplication_id: Option<String>,
    pub message_group_id: Option<String>,
    pub message_system_attributes: BTreeMap<String, MessageSystemAttributeValue>,
}

impl FromJson for SendMessageBatchRequestEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            delay_seconds: member(o, "DelaySeconds", path)?,
            id: member(o, "Id", path)?.ok_or_else(|| AwsError::missing_parameter("Id"))?,
            message_attributes: member(o, "MessageAttributes", path)?.unwrap_or_default(),
            message_body: member(o, "MessageBody", path)?
                .ok_or_else(|| AwsError::missing_parameter("MessageBody"))?,
            message_deduplication_id: member(o, "MessageDeduplicationId", path)?,
            message_group_id: member(o, "MessageGroupId", path)?,
            message_system_attributes: member(o, "MessageSystemAttributes", path)?
                .unwrap_or_default(),
        };
        Ok(s)
    }
}

impl ToJson for SendMessageBatchRequestEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.delay_seconds {
            o.insert("DelaySeconds".into(), v.to_json());
        }
        o.insert("Id".into(), self.id.to_json());
        if !self.message_attributes.is_empty() {
            o.insert(
                "MessageAttributes".into(),
                self.message_attributes.to_json(),
            );
        }
        o.insert("MessageBody".into(), self.message_body.to_json());
        if let Some(v) = &self.message_deduplication_id {
            o.insert("MessageDeduplicationId".into(), v.to_json());
        }
        if let Some(v) = &self.message_group_id {
            o.insert("MessageGroupId".into(), v.to_json());
        }
        if !self.message_system_attributes.is_empty() {
            o.insert(
                "MessageSystemAttributes".into(),
                self.message_system_attributes.to_json(),
            );
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SendMessageBatchResult {
    pub failed: Vec<BatchResultErrorEntry>,
    pub successful: Vec<SendMessageBatchResultEntry>,
}

impl FromJson for SendMessageBatchResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            failed: member(o, "Failed", path)?
                .ok_or_else(|| AwsError::missing_parameter("Failed"))?,
            successful: member(o, "Successful", path)?
                .ok_or_else(|| AwsError::missing_parameter("Successful"))?,
        };
        Ok(s)
    }
}

impl ToJson for SendMessageBatchResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.failed.is_empty() {
            o.insert("Failed".into(), self.failed.to_json());
        }
        if !self.successful.is_empty() {
            o.insert("Successful".into(), self.successful.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SendMessageBatchResultEntry {
    pub id: String,
    pub md5_of_message_attributes: Option<String>,
    pub md5_of_message_body: String,
    pub md5_of_message_system_attributes: Option<String>,
    pub message_id: String,
    pub sequence_number: Option<String>,
}

impl FromJson for SendMessageBatchResultEntry {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            id: member(o, "Id", path)?.ok_or_else(|| AwsError::missing_parameter("Id"))?,
            md5_of_message_attributes: member(o, "MD5OfMessageAttributes", path)?,
            md5_of_message_body: member(o, "MD5OfMessageBody", path)?
                .ok_or_else(|| AwsError::missing_parameter("MD5OfMessageBody"))?,
            md5_of_message_system_attributes: member(o, "MD5OfMessageSystemAttributes", path)?,
            message_id: member(o, "MessageId", path)?
                .ok_or_else(|| AwsError::missing_parameter("MessageId"))?,
            sequence_number: member(o, "SequenceNumber", path)?,
        };
        Ok(s)
    }
}

impl ToJson for SendMessageBatchResultEntry {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("Id".into(), self.id.to_json());
        if let Some(v) = &self.md5_of_message_attributes {
            o.insert("MD5OfMessageAttributes".into(), v.to_json());
        }
        o.insert(
            "MD5OfMessageBody".into(),
            self.md5_of_message_body.to_json(),
        );
        if let Some(v) = &self.md5_of_message_system_attributes {
            o.insert("MD5OfMessageSystemAttributes".into(), v.to_json());
        }
        o.insert("MessageId".into(), self.message_id.to_json());
        if let Some(v) = &self.sequence_number {
            o.insert("SequenceNumber".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SendMessageRequest {
    pub delay_seconds: Option<i32>,
    pub message_attributes: BTreeMap<String, MessageAttributeValue>,
    pub message_body: String,
    pub message_deduplication_id: Option<String>,
    pub message_group_id: Option<String>,
    pub message_system_attributes: BTreeMap<String, MessageSystemAttributeValue>,
    pub queue_url: String,
}

impl FromJson for SendMessageRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            delay_seconds: member(o, "DelaySeconds", path)?,
            message_attributes: member(o, "MessageAttributes", path)?.unwrap_or_default(),
            message_body: member(o, "MessageBody", path)?
                .ok_or_else(|| AwsError::missing_parameter("MessageBody"))?,
            message_deduplication_id: member(o, "MessageDeduplicationId", path)?,
            message_group_id: member(o, "MessageGroupId", path)?,
            message_system_attributes: member(o, "MessageSystemAttributes", path)?
                .unwrap_or_default(),
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for SendMessageRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.delay_seconds {
            o.insert("DelaySeconds".into(), v.to_json());
        }
        if !self.message_attributes.is_empty() {
            o.insert(
                "MessageAttributes".into(),
                self.message_attributes.to_json(),
            );
        }
        o.insert("MessageBody".into(), self.message_body.to_json());
        if let Some(v) = &self.message_deduplication_id {
            o.insert("MessageDeduplicationId".into(), v.to_json());
        }
        if let Some(v) = &self.message_group_id {
            o.insert("MessageGroupId".into(), v.to_json());
        }
        if !self.message_system_attributes.is_empty() {
            o.insert(
                "MessageSystemAttributes".into(),
                self.message_system_attributes.to_json(),
            );
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SendMessageResult {
    pub md5_of_message_attributes: Option<String>,
    pub md5_of_message_body: Option<String>,
    pub md5_of_message_system_attributes: Option<String>,
    pub message_id: Option<String>,
    pub sequence_number: Option<String>,
}

impl FromJson for SendMessageResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            md5_of_message_attributes: member(o, "MD5OfMessageAttributes", path)?,
            md5_of_message_body: member(o, "MD5OfMessageBody", path)?,
            md5_of_message_system_attributes: member(o, "MD5OfMessageSystemAttributes", path)?,
            message_id: member(o, "MessageId", path)?,
            sequence_number: member(o, "SequenceNumber", path)?,
        };
        Ok(s)
    }
}

impl ToJson for SendMessageResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.md5_of_message_attributes {
            o.insert("MD5OfMessageAttributes".into(), v.to_json());
        }
        if let Some(v) = &self.md5_of_message_body {
            o.insert("MD5OfMessageBody".into(), v.to_json());
        }
        if let Some(v) = &self.md5_of_message_system_attributes {
            o.insert("MD5OfMessageSystemAttributes".into(), v.to_json());
        }
        if let Some(v) = &self.message_id {
            o.insert("MessageId".into(), v.to_json());
        }
        if let Some(v) = &self.sequence_number {
            o.insert("SequenceNumber".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SetQueueAttributesRequest {
    pub attributes: BTreeMap<String, String>,
    pub queue_url: String,
}

impl FromJson for SetQueueAttributesRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            attributes: member(o, "Attributes", path)?
                .ok_or_else(|| AwsError::missing_parameter("Attributes"))?,
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
        };
        Ok(s)
    }
}

impl ToJson for SetQueueAttributesRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if !self.attributes.is_empty() {
            o.insert("Attributes".into(), self.attributes.to_json());
        }
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct StartMessageMoveTaskRequest {
    pub destination_arn: Option<String>,
    pub max_number_of_messages_per_second: Option<i32>,
    pub source_arn: String,
}

impl FromJson for StartMessageMoveTaskRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            destination_arn: member(o, "DestinationArn", path)?,
            max_number_of_messages_per_second: member(o, "MaxNumberOfMessagesPerSecond", path)?,
            source_arn: member(o, "SourceArn", path)?
                .ok_or_else(|| AwsError::missing_parameter("SourceArn"))?,
        };
        Ok(s)
    }
}

impl ToJson for StartMessageMoveTaskRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.destination_arn {
            o.insert("DestinationArn".into(), v.to_json());
        }
        if let Some(v) = &self.max_number_of_messages_per_second {
            o.insert("MaxNumberOfMessagesPerSecond".into(), v.to_json());
        }
        o.insert("SourceArn".into(), self.source_arn.to_json());
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct StartMessageMoveTaskResult {
    pub task_handle: Option<String>,
}

impl FromJson for StartMessageMoveTaskResult {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            task_handle: member(o, "TaskHandle", path)?,
        };
        Ok(s)
    }
}

impl ToJson for StartMessageMoveTaskResult {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        if let Some(v) = &self.task_handle {
            o.insert("TaskHandle".into(), v.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TagQueueRequest {
    pub queue_url: String,
    pub tags: BTreeMap<String, String>,
}

impl FromJson for TagQueueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
            tags: member(o, "Tags", path)?.ok_or_else(|| AwsError::missing_parameter("Tags"))?,
        };
        Ok(s)
    }
}

impl ToJson for TagQueueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        if !self.tags.is_empty() {
            o.insert("Tags".into(), self.tags.to_json());
        }
        Value::Object(o)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UntagQueueRequest {
    pub queue_url: String,
    pub tag_keys: Vec<String>,
}

impl FromJson for UntagQueueRequest {
    fn from_json(v: &Value, path: &str) -> Result<Self, AwsError> {
        let o = as_object(v, path)?;
        let s = Self {
            queue_url: member(o, "QueueUrl", path)?
                .ok_or_else(|| AwsError::missing_parameter("QueueUrl"))?,
            tag_keys: member(o, "TagKeys", path)?
                .ok_or_else(|| AwsError::missing_parameter("TagKeys"))?,
        };
        Ok(s)
    }
}

impl ToJson for UntagQueueRequest {
    fn to_json(&self) -> Value {
        let mut o = Map::new();
        o.insert("QueueUrl".into(), self.queue_url.to_json());
        if !self.tag_keys.is_empty() {
            o.insert("TagKeys".into(), self.tag_keys.to_json());
        }
        Value::Object(o)
    }
}

/// Implement the operations you support; the rest answer `NotImplemented`.
pub trait Service: Send + Sync {
    fn add_permission(
        &self,
        ctx: &RequestContext,
        input: AddPermissionRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "AddPermission"))
    }
    fn cancel_message_move_task(
        &self,
        ctx: &RequestContext,
        input: CancelMessageMoveTaskRequest,
    ) -> Result<CancelMessageMoveTaskResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "CancelMessageMoveTask"))
    }
    fn change_message_visibility(
        &self,
        ctx: &RequestContext,
        input: ChangeMessageVisibilityRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "ChangeMessageVisibility"))
    }
    fn change_message_visibility_batch(
        &self,
        ctx: &RequestContext,
        input: ChangeMessageVisibilityBatchRequest,
    ) -> Result<ChangeMessageVisibilityBatchResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "sqs",
            "ChangeMessageVisibilityBatch",
        ))
    }
    fn create_queue(
        &self,
        ctx: &RequestContext,
        input: CreateQueueRequest,
    ) -> Result<CreateQueueResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "CreateQueue"))
    }
    fn delete_message(
        &self,
        ctx: &RequestContext,
        input: DeleteMessageRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "DeleteMessage"))
    }
    fn delete_message_batch(
        &self,
        ctx: &RequestContext,
        input: DeleteMessageBatchRequest,
    ) -> Result<DeleteMessageBatchResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "DeleteMessageBatch"))
    }
    fn delete_queue(
        &self,
        ctx: &RequestContext,
        input: DeleteQueueRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "DeleteQueue"))
    }
    fn get_queue_attributes(
        &self,
        ctx: &RequestContext,
        input: GetQueueAttributesRequest,
    ) -> Result<GetQueueAttributesResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "GetQueueAttributes"))
    }
    fn get_queue_url(
        &self,
        ctx: &RequestContext,
        input: GetQueueUrlRequest,
    ) -> Result<GetQueueUrlResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "GetQueueUrl"))
    }
    fn list_dead_letter_source_queues(
        &self,
        ctx: &RequestContext,
        input: ListDeadLetterSourceQueuesRequest,
    ) -> Result<ListDeadLetterSourceQueuesResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "sqs",
            "ListDeadLetterSourceQueues",
        ))
    }
    fn list_message_move_tasks(
        &self,
        ctx: &RequestContext,
        input: ListMessageMoveTasksRequest,
    ) -> Result<ListMessageMoveTasksResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "ListMessageMoveTasks"))
    }
    fn list_queue_tags(
        &self,
        ctx: &RequestContext,
        input: ListQueueTagsRequest,
    ) -> Result<ListQueueTagsResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "ListQueueTags"))
    }
    fn list_queues(
        &self,
        ctx: &RequestContext,
        input: ListQueuesRequest,
    ) -> Result<ListQueuesResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "ListQueues"))
    }
    fn purge_queue(&self, ctx: &RequestContext, input: PurgeQueueRequest) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "PurgeQueue"))
    }
    fn receive_message(
        &self,
        ctx: &RequestContext,
        input: ReceiveMessageRequest,
    ) -> Result<ReceiveMessageResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "ReceiveMessage"))
    }
    fn remove_permission(
        &self,
        ctx: &RequestContext,
        input: RemovePermissionRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "RemovePermission"))
    }
    fn send_message(
        &self,
        ctx: &RequestContext,
        input: SendMessageRequest,
    ) -> Result<SendMessageResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "SendMessage"))
    }
    fn send_message_batch(
        &self,
        ctx: &RequestContext,
        input: SendMessageBatchRequest,
    ) -> Result<SendMessageBatchResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "SendMessageBatch"))
    }
    fn set_queue_attributes(
        &self,
        ctx: &RequestContext,
        input: SetQueueAttributesRequest,
    ) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "SetQueueAttributes"))
    }
    fn start_message_move_task(
        &self,
        ctx: &RequestContext,
        input: StartMessageMoveTaskRequest,
    ) -> Result<StartMessageMoveTaskResult, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "StartMessageMoveTask"))
    }
    fn tag_queue(&self, ctx: &RequestContext, input: TagQueueRequest) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "TagQueue"))
    }
    fn untag_queue(&self, ctx: &RequestContext, input: UntagQueueRequest) -> Result<(), AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sqs", "UntagQueue"))
    }
}

pub fn dispatch<S: Service + ?Sized>(
    svc: &S,
    ctx: &RequestContext,
    operation: &str,
    body: &Value,
) -> Result<RawResponse, AwsError> {
    match operation {
        "AddPermission" => {
            let output = svc.add_permission(ctx, AddPermissionRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "CancelMessageMoveTask" => {
            let output = svc.cancel_message_move_task(
                ctx,
                CancelMessageMoveTaskRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ChangeMessageVisibility" => {
            let output = svc.change_message_visibility(
                ctx,
                ChangeMessageVisibilityRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "ChangeMessageVisibilityBatch" => {
            let output = svc.change_message_visibility_batch(
                ctx,
                ChangeMessageVisibilityBatchRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "CreateQueue" => {
            let output = svc.create_queue(ctx, CreateQueueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "DeleteMessage" => {
            let output = svc.delete_message(ctx, DeleteMessageRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "DeleteMessageBatch" => {
            let output =
                svc.delete_message_batch(ctx, DeleteMessageBatchRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "DeleteQueue" => {
            let output = svc.delete_queue(ctx, DeleteQueueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "GetQueueAttributes" => {
            let output =
                svc.get_queue_attributes(ctx, GetQueueAttributesRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "GetQueueUrl" => {
            let output = svc.get_queue_url(ctx, GetQueueUrlRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ListDeadLetterSourceQueues" => {
            let output = svc.list_dead_letter_source_queues(
                ctx,
                ListDeadLetterSourceQueuesRequest::from_json(body, "")?,
            )?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ListMessageMoveTasks" => {
            let output = svc
                .list_message_move_tasks(ctx, ListMessageMoveTasksRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ListQueueTags" => {
            let output = svc.list_queue_tags(ctx, ListQueueTagsRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "ListQueues" => {
            let output = svc.list_queues(ctx, ListQueuesRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "PurgeQueue" => {
            let output = svc.purge_queue(ctx, PurgeQueueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "ReceiveMessage" => {
            let output = svc.receive_message(ctx, ReceiveMessageRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "RemovePermission" => {
            let output =
                svc.remove_permission(ctx, RemovePermissionRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "SendMessage" => {
            let output = svc.send_message(ctx, SendMessageRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "SendMessageBatch" => {
            let output =
                svc.send_message_batch(ctx, SendMessageBatchRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "SetQueueAttributes" => {
            let output =
                svc.set_queue_attributes(ctx, SetQueueAttributesRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "StartMessageMoveTask" => {
            let output = svc
                .start_message_move_task(ctx, StartMessageMoveTaskRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &output.to_json(),
            ))
        }
        "TagQueue" => {
            let output = svc.tag_queue(ctx, TagQueueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        "UntagQueue" => {
            let output = svc.untag_queue(ctx, UntagQueueRequest::from_json(body, "")?)?;
            Ok(json_response(
                JSON_VERSION,
                &ctx.request_id,
                &Value::Object(Map::new()),
            ))
        }
        other => Err(AwsError::invalid_action(other)),
    }
}
