[package]
name = "roto-svc-sqs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hex = "0.4.3"
md-5 = "0.11.0"
roto-core = { version = "0.0.1", path = "../roto-core" }
roto-protocol = { version = "0.0.1", path = "../roto-protocol" }
serde_json = "1.0.151"
uuid = { version = "1.27.0", features = ["v4"] }
