// @generated by roto-codegen from the botocore model. DO NOT EDIT.
#![allow(clippy::all, dead_code, unused_variables, unused_mut, unused_imports)]

use roto_core::{AwsError, RawResponse, RequestContext};
use roto_protocol::query::join_key;
use roto_protocol::{QueryParams, QueryValue, Timestamp, XmlValue, XmlWriter, query_response};

pub const NAMESPACE: &str = "https://sts.amazonaws.com/doc/2011-06-15/";
pub const API_VERSION: &str = "2011-06-15";

/// (operation, supported by the generated codec)
pub const OPERATIONS: &[(&str, bool)] = &[
    ("AssumeRole", true),
    ("AssumeRoleWithSAML", true),
    ("AssumeRoleWithWebIdentity", true),
    ("DecodeAuthorizationMessage", true),
    ("GetAccessKeyInfo", true),
    ("GetCallerIdentity", true),
    ("GetFederationToken", true),
    ("GetSessionToken", true),
];

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AssumeRoleRequest {
    pub duration_seconds: Option<i32>,
    pub external_id: Option<String>,
    pub policy: Option<String>,
    pub policy_arns: Vec<PolicyDescriptorType>,
    pub provided_contexts: Vec<ProvidedContext>,
    pub role_arn: String,
    pub role_session_name: String,
    pub serial_number: Option<String>,
    pub source_identity: Option<String>,
    pub tags: Vec<Tag>,
    pub token_code: Option<String>,
    pub transitive_tag_keys: Vec<String>,
}

impl QueryValue for AssumeRoleRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for AssumeRoleRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl AssumeRoleRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            duration_seconds: p.value(prefix, "DurationSeconds")?,
            external_id: p.value(prefix, "ExternalId")?,
            policy: p.value(prefix, "Policy")?,
            policy_arns: p.list(prefix, "PolicyArns", "member", false)?,
            provided_contexts: p.list(prefix, "ProvidedContexts", "member", false)?,
            role_arn: p
                .value(prefix, "RoleArn")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "RoleArn")))?,
            role_session_name: p
                .value(prefix, "RoleSessionName")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "RoleSessionName")))?,
            serial_number: p.value(prefix, "SerialNumber")?,
            source_identity: p.value(prefix, "SourceIdentity")?,
            tags: p.list(prefix, "Tags", "member", false)?,
            token_code: p.value(prefix, "TokenCode")?,
            transitive_tag_keys: p.list(prefix, "TransitiveTagKeys", "member", false)?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.duration_seconds {
            v.write(w, "DurationSeconds");
        }
        if let Some(v) = &self.external_id {
            v.write(w, "ExternalId");
        }
        if let Some(v) = &self.policy {
            v.write(w, "Policy");
        }
        w.list("PolicyArns", "member", false, &self.policy_arns);
        w.list("ProvidedContexts", "member", false, &self.provided_contexts);
        self.role_arn.write(w, "RoleArn");
        self.role_session_name.write(w, "RoleSessionName");
        if let Some(v) = &self.serial_number {
            v.write(w, "SerialNumber");
        }
        if let Some(v) = &self.source_identity {
            v.write(w, "SourceIdentity");
        }
        w.list("Tags", "member", false, &self.tags);
        if let Some(v) = &self.token_code {
            v.write(w, "TokenCode");
        }
        w.list(
            "TransitiveTagKeys",
            "member",
            false,
            &self.transitive_tag_keys,
        );
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AssumeRoleResponse {
    pub assumed_role_user: Option<AssumedRoleUser>,
    pub credentials: Option<Credentials>,
    pub packed_policy_size: Option<i32>,
    pub source_identity: Option<String>,
}

impl QueryValue for AssumeRoleResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for AssumeRoleResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl AssumeRoleResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            assumed_role_user: p.value(prefix, "AssumedRoleUser")?,
            credentials: p.value(prefix, "Credentials")?,
            packed_policy_size: p.value(prefix, "PackedPolicySize")?,
            source_identity: p.value(prefix, "SourceIdentity")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.assumed_role_user {
            v.write(w, "AssumedRoleUser");
        }
        if let Some(v) = &self.credentials {
            v.write(w, "Credentials");
        }
        if let Some(v) = &self.packed_policy_size {
            v.write(w, "PackedPolicySize");
        }
        if let Some(v) = &self.source_identity {
            v.write(w, "SourceIdentity");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AssumeRoleWithSAMLRequest {
    pub duration_seconds: Option<i32>,
    pub policy: Option<String>,
    pub policy_arns: Vec<PolicyDescriptorType>,
    pub principal_arn: String,
    pub role_arn: String,
    pub saml_assertion: String,
}

impl QueryValue for AssumeRoleWithSAMLRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for AssumeRoleWithSAMLRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl AssumeRoleWithSAMLRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            duration_seconds: p.value(prefix, "DurationSeconds")?,
            policy: p.value(prefix, "Policy")?,
            policy_arns: p.list(prefix, "PolicyArns", "member", false)?,
            principal_arn: p
                .value(prefix, "PrincipalArn")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "PrincipalArn")))?,
            role_arn: p
                .value(prefix, "RoleArn")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "RoleArn")))?,
            saml_assertion: p
                .value(prefix, "SAMLAssertion")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "SAMLAssertion")))?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.duration_seconds {
            v.write(w, "DurationSeconds");
        }
        if let Some(v) = &self.policy {
            v.write(w, "Policy");
        }
        w.list("PolicyArns", "member", false, &self.policy_arns);
        self.principal_arn.write(w, "PrincipalArn");
        self.role_arn.write(w, "RoleArn");
        self.saml_assertion.write(w, "SAMLAssertion");
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AssumeRoleWithSAMLResponse {
    pub assumed_role_user: Option<AssumedRoleUser>,
    pub audience: Option<String>,
    pub credentials: Option<Credentials>,
    pub issuer: Option<String>,
    pub name_qualifier: Option<String>,
    pub packed_policy_size: Option<i32>,
    pub source_identity: Option<String>,
    pub subject: Option<String>,
    pub subject_type: Option<String>,
}

impl QueryValue for AssumeRoleWithSAMLResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for AssumeRoleWithSAMLResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl AssumeRoleWithSAMLResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            assumed_role_user: p.value(prefix, "AssumedRoleUser")?,
            audience: p.value(prefix, "Audience")?,
            credentials: p.value(prefix, "Credentials")?,
            issuer: p.value(prefix, "Issuer")?,
            name_qualifier: p.value(prefix, "NameQualifier")?,
            packed_policy_size: p.value(prefix, "PackedPolicySize")?,
            source_identity: p.value(prefix, "SourceIdentity")?,
            subject: p.value(prefix, "Subject")?,
            subject_type: p.value(prefix, "SubjectType")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.assumed_role_user {
            v.write(w, "AssumedRoleUser");
        }
        if let Some(v) = &self.audience {
            v.write(w, "Audience");
        }
        if let Some(v) = &self.credentials {
            v.write(w, "Credentials");
        }
        if let Some(v) = &self.issuer {
            v.write(w, "Issuer");
        }
        if let Some(v) = &self.name_qualifier {
            v.write(w, "NameQualifier");
        }
        if let Some(v) = &self.packed_policy_size {
            v.write(w, "PackedPolicySize");
        }
        if let Some(v) = &self.source_identity {
            v.write(w, "SourceIdentity");
        }
        if let Some(v) = &self.subject {
            v.write(w, "Subject");
        }
        if let Some(v) = &self.subject_type {
            v.write(w, "SubjectType");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AssumeRoleWithWebIdentityRequest {
    pub duration_seconds: Option<i32>,
    pub policy: Option<String>,
    pub policy_arns: Vec<PolicyDescriptorType>,
    pub provider_id: Option<String>,
    pub role_arn: String,
    pub role_session_name: String,
    pub web_identity_token: String,
}

impl QueryValue for AssumeRoleWithWebIdentityRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for AssumeRoleWithWebIdentityRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl AssumeRoleWithWebIdentityRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            duration_seconds: p.value(prefix, "DurationSeconds")?,
            policy: p.value(prefix, "Policy")?,
            policy_arns: p.list(prefix, "PolicyArns", "member", false)?,
            provider_id: p.value(prefix, "ProviderId")?,
            role_arn: p
                .value(prefix, "RoleArn")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "RoleArn")))?,
            role_session_name: p
                .value(prefix, "RoleSessionName")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "RoleSessionName")))?,
            web_identity_token: p.value(prefix, "WebIdentityToken")?.ok_or_else(|| {
                AwsError::missing_parameter(&join_key(prefix, "WebIdentityToken"))
            })?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.duration_seconds {
            v.write(w, "DurationSeconds");
        }
        if let Some(v) = &self.policy {
            v.write(w, "Policy");
        }
        w.list("PolicyArns", "member", false, &self.policy_arns);
        if let Some(v) = &self.provider_id {
            v.write(w, "ProviderId");
        }
        self.role_arn.write(w, "RoleArn");
        self.role_session_name.write(w, "RoleSessionName");
        self.web_identity_token.write(w, "WebIdentityToken");
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AssumeRoleWithWebIdentityResponse {
    pub assumed_role_user: Option<AssumedRoleUser>,
    pub audience: Option<String>,
    pub credentials: Option<Credentials>,
    pub packed_policy_size: Option<i32>,
    pub provider: Option<String>,
    pub source_identity: Option<String>,
    pub subject_from_web_identity_token: Option<String>,
}

impl QueryValue for AssumeRoleWithWebIdentityResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for AssumeRoleWithWebIdentityResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl AssumeRoleWithWebIdentityResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            assumed_role_user: p.value(prefix, "AssumedRoleUser")?,
            audience: p.value(prefix, "Audience")?,
            credentials: p.value(prefix, "Credentials")?,
            packed_policy_size: p.value(prefix, "PackedPolicySize")?,
            provider: p.value(prefix, "Provider")?,
            source_identity: p.value(prefix, "SourceIdentity")?,
            subject_from_web_identity_token: p.value(prefix, "SubjectFromWebIdentityToken")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.assumed_role_user {
            v.write(w, "AssumedRoleUser");
        }
        if let Some(v) = &self.audience {
            v.write(w, "Audience");
        }
        if let Some(v) = &self.credentials {
            v.write(w, "Credentials");
        }
        if let Some(v) = &self.packed_policy_size {
            v.write(w, "PackedPolicySize");
        }
        if let Some(v) = &self.provider {
            v.write(w, "Provider");
        }
        if let Some(v) = &self.source_identity {
            v.write(w, "SourceIdentity");
        }
        if let Some(v) = &self.subject_from_web_identity_token {
            v.write(w, "SubjectFromWebIdentityToken");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AssumedRoleUser {
    pub arn: String,
    pub assumed_role_id: String,
}

impl QueryValue for AssumedRoleUser {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for AssumedRoleUser {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl AssumedRoleUser {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            arn: p
                .value(prefix, "Arn")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "Arn")))?,
            assumed_role_id: p
                .value(prefix, "AssumedRoleId")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "AssumedRoleId")))?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        self.arn.write(w, "Arn");
        self.assumed_role_id.write(w, "AssumedRoleId");
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Credentials {
    pub access_key_id: String,
    pub expiration: Timestamp,
    pub secret_access_key: String,
    pub session_token: String,
}

impl QueryValue for Credentials {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for Credentials {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl Credentials {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            access_key_id: p
                .value(prefix, "AccessKeyId")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "AccessKeyId")))?,
            expiration: p
                .value(prefix, "Expiration")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "Expiration")))?,
            secret_access_key: p
                .value(prefix, "SecretAccessKey")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "SecretAccessKey")))?,
            session_token: p
                .value(prefix, "SessionToken")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "SessionToken")))?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        self.access_key_id.write(w, "AccessKeyId");
        self.expiration.write(w, "Expiration");
        self.secret_access_key.write(w, "SecretAccessKey");
        self.session_token.write(w, "SessionToken");
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecodeAuthorizationMessageRequest {
    pub encoded_message: String,
}

impl QueryValue for DecodeAuthorizationMessageRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for DecodeAuthorizationMessageRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl DecodeAuthorizationMessageRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            encoded_message: p
                .value(prefix, "EncodedMessage")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "EncodedMessage")))?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        self.encoded_message.write(w, "EncodedMessage");
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecodeAuthorizationMessageResponse {
    pub decoded_message: Option<String>,
}

impl QueryValue for DecodeAuthorizationMessageResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for DecodeAuthorizationMessageResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl DecodeAuthorizationMessageResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            decoded_message: p.value(prefix, "DecodedMessage")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.decoded_message {
            v.write(w, "DecodedMessage");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FederatedUser {
    pub arn: String,
    pub federated_user_id: String,
}

impl QueryValue for FederatedUser {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for FederatedUser {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl FederatedUser {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            arn: p
                .value(prefix, "Arn")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "Arn")))?,
            federated_user_id: p
                .value(prefix, "FederatedUserId")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "FederatedUserId")))?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        self.arn.write(w, "Arn");
        self.federated_user_id.write(w, "FederatedUserId");
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetAccessKeyInfoRequest {
    pub access_key_id: String,
}

impl QueryValue for GetAccessKeyInfoRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetAccessKeyInfoRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetAccessKeyInfoRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            access_key_id: p
                .value(prefix, "AccessKeyId")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "AccessKeyId")))?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        self.access_key_id.write(w, "AccessKeyId");
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetAccessKeyInfoResponse {
    pub account: Option<String>,
}

impl QueryValue for GetAccessKeyInfoResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetAccessKeyInfoResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetAccessKeyInfoResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            account: p.value(prefix, "Account")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.account {
            v.write(w, "Account");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetCallerIdentityRequest {}

impl QueryValue for GetCallerIdentityRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetCallerIdentityRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetCallerIdentityRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {};
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {}
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetCallerIdentityResponse {
    pub account: Option<String>,
    pub arn: Option<String>,
    pub user_id: Option<String>,
}

impl QueryValue for GetCallerIdentityResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetCallerIdentityResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetCallerIdentityResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            account: p.value(prefix, "Account")?,
            arn: p.value(prefix, "Arn")?,
            user_id: p.value(prefix, "UserId")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.account {
            v.write(w, "Account");
        }
        if let Some(v) = &self.arn {
            v.write(w, "Arn");
        }
        if let Some(v) = &self.user_id {
            v.write(w, "UserId");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetFederationTokenRequest {
    pub duration_seconds: Option<i32>,
    pub name: String,
    pub policy: Option<String>,
    pub policy_arns: Vec<PolicyDescriptorType>,
    pub tags: Vec<Tag>,
}

impl QueryValue for GetFederationTokenRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetFederationTokenRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetFederationTokenRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            duration_seconds: p.value(prefix, "DurationSeconds")?,
            name: p
                .value(prefix, "Name")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "Name")))?,
            policy: p.value(prefix, "Policy")?,
            policy_arns: p.list(prefix, "PolicyArns", "member", false)?,
            tags: p.list(prefix, "Tags", "member", false)?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.duration_seconds {
            v.write(w, "DurationSeconds");
        }
        self.name.write(w, "Name");
        if let Some(v) = &self.policy {
            v.write(w, "Policy");
        }
        w.list("PolicyArns", "member", false, &self.policy_arns);
        w.list("Tags", "member", false, &self.tags);
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetFederationTokenResponse {
    pub credentials: Option<Credentials>,
    pub federated_user: Option<FederatedUser>,
    pub packed_policy_size: Option<i32>,
}

impl QueryValue for GetFederationTokenResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetFederationTokenResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetFederationTokenResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            credentials: p.value(prefix, "Credentials")?,
            federated_user: p.value(prefix, "FederatedUser")?,
            packed_policy_size: p.value(prefix, "PackedPolicySize")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.credentials {
            v.write(w, "Credentials");
        }
        if let Some(v) = &self.federated_user {
            v.write(w, "FederatedUser");
        }
        if let Some(v) = &self.packed_policy_size {
            v.write(w, "PackedPolicySize");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetSessionTokenRequest {
    pub duration_seconds: Option<i32>,
    pub serial_number: Option<String>,
    pub token_code: Option<String>,
}

impl QueryValue for GetSessionTokenRequest {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetSessionTokenRequest {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetSessionTokenRequest {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            duration_seconds: p.value(prefix, "DurationSeconds")?,
            serial_number: p.value(prefix, "SerialNumber")?,
            token_code: p.value(prefix, "TokenCode")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.duration_seconds {
            v.write(w, "DurationSeconds");
        }
        if let Some(v) = &self.serial_number {
            v.write(w, "SerialNumber");
        }
        if let Some(v) = &self.token_code {
            v.write(w, "TokenCode");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetSessionTokenResponse {
    pub credentials: Option<Credentials>,
}

impl QueryValue for GetSessionTokenResponse {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for GetSessionTokenResponse {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl GetSessionTokenResponse {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            credentials: p.value(prefix, "Credentials")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.credentials {
            v.write(w, "Credentials");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PolicyDescriptorType {
    pub arn: Option<String>,
}

impl QueryValue for PolicyDescriptorType {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for PolicyDescriptorType {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl PolicyDescriptorType {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            arn: p.value(prefix, "arn")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.arn {
            v.write(w, "arn");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvidedContext {
    pub context_assertion: Option<String>,
    pub provider_arn: Option<String>,
}

impl QueryValue for ProvidedContext {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for ProvidedContext {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl ProvidedContext {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            context_assertion: p.value(prefix, "ContextAssertion")?,
            provider_arn: p.value(prefix, "ProviderArn")?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        if let Some(v) = &self.context_assertion {
            v.write(w, "ContextAssertion");
        }
        if let Some(v) = &self.provider_arn {
            v.write(w, "ProviderArn");
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Tag {
    pub key: String,
    pub value: String,
}

impl QueryValue for Tag {
    fn read(p: &QueryParams, key: &str) -> Result<Option<Self>, AwsError> {
        if !p.has_prefix(key) {
            return Ok(None);
        }
        Ok(Some(Self::read_members(p, key)?))
    }
}

impl XmlValue for Tag {
    fn write(&self, w: &mut XmlWriter, name: &str) {
        w.open(name);
        self.write_members(w);
        w.close(name);
    }
}

impl Tag {
    pub fn read_members(p: &QueryParams, prefix: &str) -> Result<Self, AwsError> {
        let s = Self {
            key: p
                .value(prefix, "Key")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "Key")))?,
            value: p
                .value(prefix, "Value")?
                .ok_or_else(|| AwsError::missing_parameter(&join_key(prefix, "Value")))?,
        };
        Ok(s)
    }

    pub fn write_members(&self, w: &mut XmlWriter) {
        self.key.write(w, "Key");
        self.value.write(w, "Value");
    }
}

/// Implement the operations you support; the rest answer `NotImplemented`.
pub trait Service: Send + Sync {
    fn assume_role(
        &self,
        ctx: &RequestContext,
        input: AssumeRoleRequest,
    ) -> Result<AssumeRoleResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sts", "AssumeRole"))
    }
    fn assume_role_with_saml(
        &self,
        ctx: &RequestContext,
        input: AssumeRoleWithSAMLRequest,
    ) -> Result<AssumeRoleWithSAMLResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sts", "AssumeRoleWithSAML"))
    }
    fn assume_role_with_web_identity(
        &self,
        ctx: &RequestContext,
        input: AssumeRoleWithWebIdentityRequest,
    ) -> Result<AssumeRoleWithWebIdentityResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "sts",
            "AssumeRoleWithWebIdentity",
        ))
    }
    fn decode_authorization_message(
        &self,
        ctx: &RequestContext,
        input: DecodeAuthorizationMessageRequest,
    ) -> Result<DecodeAuthorizationMessageResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented(
            "sts",
            "DecodeAuthorizationMessage",
        ))
    }
    fn get_access_key_info(
        &self,
        ctx: &RequestContext,
        input: GetAccessKeyInfoRequest,
    ) -> Result<GetAccessKeyInfoResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sts", "GetAccessKeyInfo"))
    }
    fn get_caller_identity(
        &self,
        ctx: &RequestContext,
        input: GetCallerIdentityRequest,
    ) -> Result<GetCallerIdentityResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sts", "GetCallerIdentity"))
    }
    fn get_federation_token(
        &self,
        ctx: &RequestContext,
        input: GetFederationTokenRequest,
    ) -> Result<GetFederationTokenResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sts", "GetFederationToken"))
    }
    fn get_session_token(
        &self,
        ctx: &RequestContext,
        input: GetSessionTokenRequest,
    ) -> Result<GetSessionTokenResponse, AwsError> {
        let _ = (ctx, input);
        Err(AwsError::not_implemented("sts", "GetSessionToken"))
    }
}

pub fn dispatch<S: Service + ?Sized>(
    svc: &S,
    ctx: &RequestContext,
    action: &str,
    params: &QueryParams,
) -> Result<RawResponse, AwsError> {
    match action {
        "AssumeRole" => {
            let output = svc.assume_role(ctx, AssumeRoleRequest::read_members(params, "")?)?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "AssumeRole",
                Some("AssumeRoleResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        "AssumeRoleWithSAML" => {
            let output = svc
                .assume_role_with_saml(ctx, AssumeRoleWithSAMLRequest::read_members(params, "")?)?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "AssumeRoleWithSAML",
                Some("AssumeRoleWithSAMLResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        "AssumeRoleWithWebIdentity" => {
            let output = svc.assume_role_with_web_identity(
                ctx,
                AssumeRoleWithWebIdentityRequest::read_members(params, "")?,
            )?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "AssumeRoleWithWebIdentity",
                Some("AssumeRoleWithWebIdentityResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        "DecodeAuthorizationMessage" => {
            let output = svc.decode_authorization_message(
                ctx,
                DecodeAuthorizationMessageRequest::read_members(params, "")?,
            )?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "DecodeAuthorizationMessage",
                Some("DecodeAuthorizationMessageResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        "GetAccessKeyInfo" => {
            let output =
                svc.get_access_key_info(ctx, GetAccessKeyInfoRequest::read_members(params, "")?)?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "GetAccessKeyInfo",
                Some("GetAccessKeyInfoResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        "GetCallerIdentity" => {
            let output =
                svc.get_caller_identity(ctx, GetCallerIdentityRequest::read_members(params, "")?)?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "GetCallerIdentity",
                Some("GetCallerIdentityResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        "GetFederationToken" => {
            let output = svc
                .get_federation_token(ctx, GetFederationTokenRequest::read_members(params, "")?)?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "GetFederationToken",
                Some("GetFederationTokenResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        "GetSessionToken" => {
            let output =
                svc.get_session_token(ctx, GetSessionTokenRequest::read_members(params, "")?)?;
            let mut w = XmlWriter::new();
            output.write_members(&mut w);
            Ok(query_response(
                NAMESPACE,
                "GetSessionToken",
                Some("GetSessionTokenResult"),
                &ctx.request_id,
                &w.finish(),
            ))
        }
        other => Err(AwsError::invalid_action(other)),
    }
}
